// Analyst Agent Story Library — T1–T11 Runtime Journey
// RSM | CATT | DCT Platform Executive Demo Environment v3.1
// Generated by the Analyst Agent from the DCT Delivery Model canonical architecture

export interface AcceptanceCriterion {
  id: string;
  text: string;
}

export interface BlitzyStep {
  step: string;
}

export interface AnalystStory {
  storyId: string;
  touchpointId: string;
  title: string;
  description: string;
  platformGuarantee: string;
  guaranteeType: "SCHEMA" | "LINEAGE" | "CONTRACT" | "RUNTIME";
  system: string;
  layer: string;
  acceptanceCriteria: AcceptanceCriterion[];
  blitzyTask: string;
  blitzySteps: BlitzyStep[];
  gate: string;
}

export const ANALYST_STORIES: AnalystStory[] = [
  {
    storyId: "DCT-S-T1",
    touchpointId: "T1",
    title: "T1 — File Upload and doc_id Assignment",
    description:
      "Receive client ERP trial balance file from Phoenix/DMS and assign an immutable document identifier (doc_id) that persists throughout the entire platform lifecycle for lineage and traceability.",
    platformGuarantee:
      "Every source file receives a unique immutable doc_id that is used for lineage and traceability across all downstream systems.",
    guaranteeType: "LINEAGE",
    system: "Phoenix / DMS",
    layer: "Data Ingestion Layer",
    acceptanceCriteria: [
      { id: "AC-T1-01", text: "File received from Phoenix/DMS ingestion endpoint" },
      { id: "AC-T1-02", text: "Immutable doc_id generated and stored in intake log" },
      { id: "AC-T1-03", text: "Intake record logged with timestamp and source system" },
      { id: "AC-T1-04", text: "Source system identity recorded in metadata" },
      { id: "AC-T1-05", text: "File routing event published to downstream consumers" },
    ],
    blitzyTask: "Generate ingestion microservice for trial balance intake with doc_id assignment.",
    blitzySteps: [
      { step: "Create ingestion endpoint accepting ERP trial balance file" },
      { step: "Generate immutable doc_id using UUID v4 strategy" },
      { step: "Log ingestion metadata: source system, timestamp, file type, size" },
      { step: "Store source file reference with doc_id binding" },
      { step: "Publish ingestion event to downstream routing queue" },
    ],
    gate: "G1 — Schema Lock",
  },
  {
    storyId: "DCT-S-T2",
    touchpointId: "T2",
    title: "T2 — File Structure Recognition",
    description:
      "AI Orchestrator analyzes the ingested file to identify its schema, classify the financial data model, and validate format conformance before extraction begins.",
    platformGuarantee:
      "Schema integrity guarantee — every file is validated against the canonical schema before any data is extracted or persisted.",
    guaranteeType: "SCHEMA",
    system: "AI Orchestrator",
    layer: "AI Orchestration Layer",
    acceptanceCriteria: [
      { id: "AC-T2-01", text: "File schema identified and classified against known financial models" },
      { id: "AC-T2-02", text: "Schema Recognition Report generated with confidence score" },
      { id: "AC-T2-03", text: "File type classification stored against doc_id" },
      { id: "AC-T2-04", text: "Format conformance validated — non-conforming files rejected with reason code" },
      { id: "AC-T2-05", text: "Recognition result published for T3 consumption" },
    ],
    blitzyTask: "Generate AI schema recognition service that classifies ERP file structure against canonical financial models.",
    blitzySteps: [
      { step: "Implement schema fingerprinting for known ERP export formats" },
      { step: "Build confidence scoring engine for schema classification" },
      { step: "Generate Schema Recognition Report with classification metadata" },
      { step: "Implement rejection handler for non-conforming files" },
      { step: "Publish recognition result event with doc_id binding" },
    ],
    gate: "G1 — Schema Lock",
  },
  {
    storyId: "DCT-S-T3",
    touchpointId: "T3",
    title: "T3 — Financial Data Extraction",
    description:
      "AI Orchestrator extracts financial data from the recognized file and applies cross-LOB normalization to produce records conforming to the PDC canonical data model.",
    platformGuarantee:
      "Schema integrity guarantee — extracted data conforms to the canonical PDC schema before persistence.",
    guaranteeType: "SCHEMA",
    system: "AI Orchestrator",
    layer: "AI Orchestration Layer",
    acceptanceCriteria: [
      { id: "AC-T3-01", text: "Financial data extracted from all recognized sections of the source file" },
      { id: "AC-T3-02", text: "Cross-LOB normalization applied to produce canonical field mapping" },
      { id: "AC-T3-03", text: "Normalization Record generated with field-level mapping log" },
      { id: "AC-T3-04", text: "Extraction log stored with doc_id and record count" },
      { id: "AC-T3-05", text: "Normalized records ready for PDC persistence at T4" },
    ],
    blitzyTask: "Generate financial data extraction and normalization service with canonical model mapping.",
    blitzySteps: [
      { step: "Build extraction engine for trial balance line items" },
      { step: "Implement cross-LOB normalization rules against canonical PDC schema" },
      { step: "Generate Normalization Record with field-level mapping audit trail" },
      { step: "Validate extracted records against PDC schema constraints" },
      { step: "Emit normalized record set for PDC persistence" },
    ],
    gate: "G1 — Schema Lock",
  },
  {
    storyId: "DCT-S-T4",
    touchpointId: "T4",
    title: "T4 — Canonical Normalization and PDC Persistence",
    description:
      "PDC receives normalized financial records and persists them as the authoritative canonical dataset. This is the first authority action — PDC becomes the system of record for the financial data.",
    platformGuarantee:
      "Canonical dataset guarantee — PDC is the single authoritative source for all financial data used downstream by TDC and Roger UI.",
    guaranteeType: "SCHEMA",
    system: "PDC",
    layer: "Financial Data Authority (PDC)",
    acceptanceCriteria: [
      { id: "AC-T4-01", text: "Normalized records persisted to PDC canonical store" },
      { id: "AC-T4-02", text: "PDC persistence confirmation returned with record count and version" },
      { id: "AC-T4-03", text: "Version record created for the canonical dataset" },
      { id: "AC-T4-04", text: "Schema Lock Certificate prerequisites satisfied" },
      { id: "AC-T4-05", text: "Canonical record set accessible for lineage capture at T5" },
    ],
    blitzyTask: "Generate PDC canonical data persistence service with version management and authority record creation.",
    blitzySteps: [
      { step: "Build PDC persistence endpoint accepting normalized record sets" },
      { step: "Implement version management for canonical dataset records" },
      { step: "Generate persistence confirmation with record count and dataset version" },
      { step: "Create canonical record index for downstream lineage access" },
      { step: "Emit dataset authority event for T5 lineage capture" },
    ],
    gate: "G2 — Invariant Lock",
  },
  {
    storyId: "DCT-S-T5",
    touchpointId: "T5",
    title: "T5 — Lineage Capture",
    description:
      "PDC captures the full data provenance graph for the canonical dataset, recording the chain from client source file through every transformation step to the persisted canonical record.",
    platformGuarantee:
      "Lineage traceability guarantee — every canonical record is traceable to its source file via an unbroken provenance chain.",
    guaranteeType: "LINEAGE",
    system: "PDC",
    layer: "Financial Data Authority (PDC)",
    acceptanceCriteria: [
      { id: "AC-T5-01", text: "Lineage graph created linking doc_id → T1 intake → T2 recognition → T3 extraction → T4 canonical record" },
      { id: "AC-T5-02", text: "Lineage Record stored with all transformation node references" },
      { id: "AC-T5-03", text: "Each canonical record linked to its lineage node" },
      { id: "AC-T5-04", text: "Lineage graph queryable by doc_id" },
      { id: "AC-T5-05", text: "Lineage Closure Certificate prerequisites satisfied" },
    ],
    blitzyTask: "Generate lineage graph capture service that records the full provenance chain for each canonical record.",
    blitzySteps: [
      { step: "Build lineage graph data model with node and edge schema" },
      { step: "Implement provenance chain builder: doc_id → T1 → T2 → T3 → T4" },
      { step: "Store Lineage Record with all transformation references" },
      { step: "Create lineage query API by doc_id and canonical record ID" },
      { step: "Emit lineage capture event for dataset authority establishment at T6" },
    ],
    gate: "G3 — Lineage Closure",
  },
  {
    storyId: "DCT-S-T6",
    touchpointId: "T6",
    title: "T6 — Canonical Dataset Establishment",
    description:
      "PDC formally establishes the canonical dataset as the authoritative financial data source for the engagement. Dataset Authority Certificate is issued and the dataset is locked from further modification.",
    platformGuarantee:
      "Canonical dataset guarantee — the established dataset is immutable and authoritative for all downstream tax processing.",
    guaranteeType: "CONTRACT",
    system: "PDC",
    layer: "Financial Data Authority (PDC)",
    acceptanceCriteria: [
      { id: "AC-T6-01", text: "Dataset Authority Certificate issued for the canonical record set" },
      { id: "AC-T6-02", text: "Canonical dataset locked — no further modifications permitted" },
      { id: "AC-T6-03", text: "Authority record stored with issuing authority and timestamp" },
      { id: "AC-T6-04", text: "Dataset version frozen and version record finalized" },
      { id: "AC-T6-05", text: "Dataset available for READY signal publication at T7" },
    ],
    blitzyTask: "Generate dataset authority establishment service with immutability enforcement and certificate issuance.",
    blitzySteps: [
      { step: "Implement dataset lock mechanism preventing further record modification" },
      { step: "Generate Dataset Authority Certificate with issuing authority metadata" },
      { step: "Freeze dataset version and finalize version record" },
      { step: "Store authority certificate in governance artifact registry" },
      { step: "Emit dataset established event for T7 READY signal" },
    ],
    gate: "G3 — Lineage Closure",
  },
  {
    storyId: "DCT-S-T7",
    touchpointId: "T7",
    title: "T7 — READY Signal to TDC",
    description:
      "PDC publishes the READY event to TDC signaling that the canonical financial dataset is established, lineage is captured, and the dataset is available for tax processing.",
    platformGuarantee:
      "Runtime guarantee — TDC only begins tax processing after receiving a verified READY signal from PDC.",
    guaranteeType: "RUNTIME",
    system: "PDC",
    layer: "Financial Data Authority (PDC)",
    acceptanceCriteria: [
      { id: "AC-T7-01", text: "READY event published to TDC event bus with dataset reference" },
      { id: "AC-T7-02", text: "Event includes doc_id, canonical dataset version, and authority certificate reference" },
      { id: "AC-T7-03", text: "TDC acknowledges READY event receipt" },
      { id: "AC-T7-04", text: "READY signal logged in platform event log with timestamp" },
      { id: "AC-T7-05", text: "Mapping readiness confirmed — AI Orchestrator notified for T8" },
    ],
    blitzyTask: "Generate READY signal publication service that notifies TDC when the canonical dataset is ready for tax processing.",
    blitzySteps: [
      { step: "Build READY event schema with dataset reference and authority certificate" },
      { step: "Implement event publication to TDC event bus" },
      { step: "Add acknowledgment handler for TDC READY receipt confirmation" },
      { step: "Log READY signal in platform governance event log" },
      { step: "Notify AI Orchestrator to begin mapping proposal generation at T8" },
    ],
    gate: "G3 — Lineage Closure",
  },
  {
    storyId: "DCT-S-T8",
    touchpointId: "T8",
    title: "T8 — AI Tax Mapping Proposals",
    description:
      "AI Orchestrator generates tax mapping proposals for the canonical financial dataset. Proposals are stateless AI outputs — they are recommendations only and do not constitute tax decisions.",
    platformGuarantee:
      "Mapping auditability guarantee — all AI mapping proposals are logged with confidence scores and are auditable by practitioners.",
    guaranteeType: "CONTRACT",
    system: "AI Orchestrator",
    layer: "AI Orchestration Layer",
    acceptanceCriteria: [
      { id: "AC-T8-01", text: "Tax mapping proposals generated for all canonical financial records" },
      { id: "AC-T8-02", text: "Each proposal includes confidence score and mapping rationale" },
      { id: "AC-T8-03", text: "Mapping Proposal Set stored in TDC with doc_id reference" },
      { id: "AC-T8-04", text: "Proposals flagged as AI-generated — not authoritative decisions" },
      { id: "AC-T8-05", text: "Proposals available for practitioner review at T9" },
    ],
    blitzyTask: "Generate AI tax mapping proposal service that produces auditable mapping recommendations from canonical financial data.",
    blitzySteps: [
      { step: "Build tax mapping inference engine using canonical record schema" },
      { step: "Implement confidence scoring for each mapping proposal" },
      { step: "Generate Mapping Proposal Set with rationale and confidence metadata" },
      { step: "Store proposals in TDC with AI-generated flag and doc_id binding" },
      { step: "Publish mapping proposals available event for T9 practitioner review" },
    ],
    gate: "G4 — Contract Publication",
  },
  {
    storyId: "DCT-S-T9",
    touchpointId: "T9",
    title: "T9 — Practitioner Tax Review",
    description:
      "Tax practitioner reviews AI-generated mapping proposals in Roger UI, validates or overrides each proposal, and approves the final tax mapping for decision persistence.",
    platformGuarantee:
      "Tax decision traceability guarantee — every tax decision is traceable to a practitioner approval action with timestamp and user identity.",
    guaranteeType: "CONTRACT",
    system: "TDC",
    layer: "Tax Decision Authority (TDC)",
    acceptanceCriteria: [
      { id: "AC-T9-01", text: "Practitioner can view all AI mapping proposals in Roger UI" },
      { id: "AC-T9-02", text: "Practitioner can validate or override each proposal" },
      { id: "AC-T9-03", text: "Override reason captured and stored with proposal record" },
      { id: "AC-T9-04", text: "Practitioner approval action logged with user identity and timestamp" },
      { id: "AC-T9-05", text: "Approved mapping set forwarded to T10 for decision persistence" },
    ],
    blitzyTask: "Generate practitioner tax review interface in Roger UI with proposal validation and override capability.",
    blitzySteps: [
      { step: "Build mapping proposal review UI in Roger UI with approve/override actions" },
      { step: "Implement override reason capture form with required field validation" },
      { step: "Log practitioner approval action with user identity and timestamp" },
      { step: "Store review record with doc_id, proposal reference, and decision" },
      { step: "Forward approved mapping set to TDC for T10 persistence" },
    ],
    gate: "G4 — Contract Publication",
  },
  {
    storyId: "DCT-S-T10",
    touchpointId: "T10",
    title: "T10 — Tax Decision Persistence",
    description:
      "TDC persists the practitioner-approved tax decisions as the authoritative tax record. This is the second authority action — TDC becomes the system of record for all tax decisions.",
    platformGuarantee:
      "Tax decision traceability guarantee — TDC is the single authoritative source for all tax decisions, traceable to practitioner approval.",
    guaranteeType: "CONTRACT",
    system: "TDC",
    layer: "Tax Decision Authority (TDC)",
    acceptanceCriteria: [
      { id: "AC-T10-01", text: "Approved tax decisions persisted to TDC authoritative store" },
      { id: "AC-T10-02", text: "Tax Decision Records created with doc_id, practitioner ID, and timestamp" },
      { id: "AC-T10-03", text: "Decision records linked to source canonical records via doc_id" },
      { id: "AC-T10-04", text: "Published Data Contracts generated for Roger UI consumption" },
      { id: "AC-T10-05", text: "Contract Publication Certificate prerequisites satisfied" },
    ],
    blitzyTask: "Generate TDC tax decision persistence service with authority record creation and contract publication.",
    blitzySteps: [
      { step: "Build TDC persistence endpoint for approved tax decision sets" },
      { step: "Create Tax Decision Records with full provenance metadata" },
      { step: "Link decision records to canonical records via doc_id" },
      { step: "Generate Published Data Contracts for Roger UI consumption" },
      { step: "Emit contract publication event for T11 UI consumption" },
    ],
    gate: "G4 — Contract Publication",
  },
  {
    storyId: "DCT-S-T11",
    touchpointId: "T11",
    title: "T11 — Practitioner UI Consumption",
    description:
      "Roger UI surfaces the published tax decisions and canonical financial data to the practitioner as a read-only consumer. Roger UI never writes to PDC or TDC.",
    platformGuarantee:
      "Runtime guarantee — Roger UI is a read-only consumer. All data displayed is sourced from Published Data Contracts issued by TDC.",
    guaranteeType: "RUNTIME",
    system: "Roger UI",
    layer: "Practitioner Experience Layer",
    acceptanceCriteria: [
      { id: "AC-T11-01", text: "Roger UI displays tax decisions from Published Data Contracts" },
      { id: "AC-T11-02", text: "Practitioner can view full lineage from source file to tax decision" },
      { id: "AC-T11-03", text: "Roger UI does not write to PDC or TDC — read-only enforcement verified" },
      { id: "AC-T11-04", text: "All displayed data sourced from TDC Published Data Contracts" },
      { id: "AC-T11-05", text: "Practitioner can export tax-ready records for downstream use" },
    ],
    blitzyTask: "Generate Roger UI read-only consumption layer for Published Data Contracts with full lineage visibility.",
    blitzySteps: [
      { step: "Build Roger UI data consumption layer reading from TDC Published Data Contracts" },
      { step: "Implement read-only enforcement — no write operations to PDC or TDC" },
      { step: "Build lineage viewer showing full chain from source file to tax decision" },
      { step: "Implement tax-ready record export functionality" },
      { step: "Add contract version indicator showing which Published Data Contract is displayed" },
    ],
    gate: "G4 — Contract Publication",
  },
];

// ─── PLATFORM GUARANTEES ─────────────────────────────────────────────────────

export interface PlatformGuarantee {
  id: string;
  name: string;
  description: string;
  type: "SCHEMA" | "LINEAGE" | "CONTRACT" | "RUNTIME";
  storyIds: string[];
  gate: string;
  color: string;
}

export const PLATFORM_GUARANTEES: PlatformGuarantee[] = [
  {
    id: "PG-01",
    name: "Schema Integrity Guarantee",
    description:
      "Every source file is validated against the canonical PDC schema before any data is extracted or persisted. Non-conforming files are rejected with a reason code.",
    type: "SCHEMA",
    storyIds: ["DCT-S-T2", "DCT-S-T3", "DCT-S-T4"],
    gate: "G1 — Schema Lock",
    color: "bg-violet-600",
  },
  {
    id: "PG-02",
    name: "Lineage Traceability Guarantee",
    description:
      "Every canonical record is traceable to its source file via an unbroken provenance chain: doc_id → T1 intake → T2 recognition → T3 extraction → T4 canonical record.",
    type: "LINEAGE",
    storyIds: ["DCT-S-T1", "DCT-S-T5"],
    gate: "G3 — Lineage Closure",
    color: "bg-emerald-600",
  },
  {
    id: "PG-03",
    name: "Canonical Dataset Guarantee",
    description:
      "PDC is the single authoritative source for all financial data. Once established at T6, the canonical dataset is immutable and all downstream systems consume only from PDC.",
    type: "CONTRACT",
    storyIds: ["DCT-S-T4", "DCT-S-T6", "DCT-S-T7"],
    gate: "G3 — Lineage Closure",
    color: "bg-blue-600",
  },
  {
    id: "PG-04",
    name: "Mapping Auditability Guarantee",
    description:
      "All AI mapping proposals are logged with confidence scores and are fully auditable by practitioners. No AI proposal is persisted as a tax decision without practitioner approval.",
    type: "CONTRACT",
    storyIds: ["DCT-S-T8", "DCT-S-T9"],
    gate: "G4 — Contract Publication",
    color: "bg-amber-600",
  },
  {
    id: "PG-05",
    name: "Tax Decision Traceability Guarantee",
    description:
      "Every tax decision in TDC is traceable to a practitioner approval action with timestamp, user identity, and the canonical financial record it was derived from.",
    type: "CONTRACT",
    storyIds: ["DCT-S-T9", "DCT-S-T10", "DCT-S-T11"],
    gate: "G4 — Contract Publication",
    color: "bg-red-600",
  },
];

// ─── HELPERS ─────────────────────────────────────────────────────────────────

export const GUARANTEE_TYPE_COLORS: Record<string, string> = {
  SCHEMA: "bg-violet-100 text-violet-800 border-violet-200",
  LINEAGE: "bg-emerald-100 text-emerald-800 border-emerald-200",
  CONTRACT: "bg-blue-100 text-blue-800 border-blue-200",
  RUNTIME: "bg-pink-100 text-pink-800 border-pink-200",
};

export const getStoriesForTouchpoint = (touchpointId: string): AnalystStory | undefined =>
  ANALYST_STORIES.find(s => s.touchpointId === touchpointId);
