CREATE TABLE `deployments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`deploymentId` varchar(32) NOT NULL,
	`releaseName` varchar(512) NOT NULL,
	`deploymentDate` varchar(16) NOT NULL,
	`deploymentOwner` varchar(128) NOT NULL,
	`productOwner` varchar(128) NOT NULL,
	`platform` enum('PDC','TDC','Platform','Both') NOT NULL,
	`type` enum('Batch','Feature','Bug','Technical Story','Hotfix') NOT NULL,
	`status` enum('Planned','Scheduled','In Progress','Deployed','Rolled Back') NOT NULL DEFAULT 'Planned',
	`summary` text,
	`releaseNotesUrl` varchar(1024),
	`swaggerUrl` varchar(1024),
	`relatedBatch` varchar(32),
	`relatedFeature` varchar(256),
	`relatedStory` varchar(256),
	`environment` varchar(64) NOT NULL DEFAULT 'Production',
	`adoWorkItemId` varchar(32),
	`githubReleaseTag` varchar(128),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `deployments_id` PRIMARY KEY(`id`),
	CONSTRAINT `deployments_deploymentId_unique` UNIQUE(`deploymentId`)
);
