// Architecture View — Platform Architecture Layers v3.1
// RSM | CATT | DCT Platform Executive Demo Environment
// Two-tab view: Visio Diagram (generated by Architecture Sync Agent) + Interactive Swimlane

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Shield, Database, Brain, ArrowDown, CheckCircle2,
  FileText, Link2, Play, GitBranch, ShieldCheck, ArrowRight, X,
  Image, Layers, Download, Maximize2, Move
} from "lucide-react";
import {
  PLATFORM_LAYERS, TOUCHPOINTS, AGENTS, getAgent, getLayer,
  ADR_REGISTRY, OPEN_ITEMS, DEPENDENCIES, ARCHITECTURE_GUARDRAILS,
  SYSTEM_OWNERSHIP, ENTRY_POINTS, INGESTION_CONTRACT, ARCH_METADATA,
  type PlatformLayer, type EnrichedTouchpoint
} from "@/lib/platformData";

// ─── AGENT ICONS ─────────────────────────────────────────────────────────────

const AGENT_ICONS: Record<string, React.ElementType> = {
  analyst: FileText, architecture: GitBranch, qa: ShieldCheck,
  demo_runner: Play, roger_ai: Brain,
};

// ─── TOUCHPOINT CHIP ─────────────────────────────────────────────────────────

const TP_STATUS_DOT: Record<string, string> = {
  COMPLETE: "bg-emerald-400", IN_PROGRESS: "bg-blue-400",
  PENDING: "bg-amber-400", PLANNED: "bg-slate-300", BLOCKED: "bg-red-400",
};

function TouchpointChip({ tp, onClick, selected }: {
  tp: EnrichedTouchpoint;
  onClick: () => void;
  selected: boolean;
}) {
  const agent = tp.agentId ? getAgent(tp.agentId) : null;
  return (
    <button
      onClick={onClick}
      className={`flex items-center gap-2 px-3 py-2 rounded-lg border transition-all text-left ${
        selected
          ? "bg-white shadow-md border-white/60 scale-105"
          : "bg-white/10 border-white/20 hover:bg-white/20"
      }`}
    >
      <div className={`w-2 h-2 rounded-full shrink-0 ${TP_STATUS_DOT[tp.status]}`} />
      <div>
        <div className={`text-xs font-bold ${selected ? "text-foreground" : "text-white"}`}>{tp.id}</div>
        <div className={`text-xs leading-tight max-w-[7rem] ${selected ? "text-muted-foreground" : "text-white/70"}`}>
          {tp.name.split(" ").slice(0, 3).join(" ")}
        </div>
        {agent && (
          <div className={`text-xs mt-0.5 ${selected ? "text-[#003A8F]" : "text-white/60"}`}>
            {agent.name.split(" ")[0]}
          </div>
        )}
      </div>
    </button>
  );
}

// ─── LAYER ROW ────────────────────────────────────────────────────────────────

function LayerRow({ layer, touchpoints, selectedTp, onSelectTp }: {
  layer: PlatformLayer;
  touchpoints: EnrichedTouchpoint[];
  selectedTp: string | null;
  onSelectTp: (id: string | null) => void;
}) {
  const layerAgents = AGENTS.filter(a => a.layerId === layer.id);

  return (
    <div className="rounded-xl overflow-hidden border border-white/10">
      {/* Header */}
      <div className={`${layer.color} px-5 py-3`}>
        <div className="flex items-center justify-between flex-wrap gap-2">
          <div className="flex items-center gap-3">
            <div>
              <div className="flex items-center gap-2 flex-wrap">
                <span className="text-sm font-bold text-white">{layer.label}</span>
                {layer.isSystemOfRecord && (
                  <span className="text-xs bg-white/20 text-white px-2 py-0.5 rounded-full font-semibold border border-white/30">
                    ◆ AUTHORITY
                  </span>
                )}
              </div>
              <div className="text-xs text-white/80 mt-0.5">{layer.sublabel}</div>
            </div>
          </div>
          <div className="flex items-center gap-2 flex-wrap">
            {layer.systems.map(s => (
              <span key={s} className="text-xs bg-white/15 text-white px-2 py-0.5 rounded border border-white/20">{s}</span>
            ))}
            <span className="text-xs bg-white/10 text-white/80 px-2 py-0.5 rounded-full border border-white/20">
              {layer.authority}
            </span>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="bg-slate-800/60 px-5 py-3">
        <div className="flex items-start gap-6 flex-wrap">
          {touchpoints.length > 0 ? (
            <div className="flex-1">
              <div className="text-xs font-semibold uppercase tracking-wider text-slate-400 mb-2">Touchpoints</div>
              <div className="flex flex-wrap gap-2">
                {touchpoints.map(tp => (
                  <TouchpointChip
                    key={tp.id} tp={tp}
                    selected={selectedTp === tp.id}
                    onClick={() => onSelectTp(selectedTp === tp.id ? null : tp.id)}
                  />
                ))}
              </div>
            </div>
          ) : (
            <div className="flex-1">
              <div className="text-xs text-slate-500 italic">Source systems — no platform touchpoints</div>
            </div>
          )}

          {layerAgents.length > 0 && (
            <div className="shrink-0">
              <div className="text-xs font-semibold uppercase tracking-wider text-slate-400 mb-2">Agents</div>
              <div className="flex flex-col gap-1.5">
                {layerAgents.map(agent => {
                  const Icon = AGENT_ICONS[agent.id] || Brain;
                  return (
                    <div key={agent.id} className="flex items-center gap-2 bg-white/10 rounded-lg px-3 py-1.5 border border-white/10">
                      <div className={`w-5 h-5 rounded ${agent.color} flex items-center justify-center`}>
                        <Icon className="w-3 h-3 text-white" />
                      </div>
                      <div>
                        <div className="text-xs font-medium text-white">{agent.name}</div>
                        <div className="text-xs text-slate-400">{agent.status}</div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// ─── TOUCHPOINT DETAIL PANEL ─────────────────────────────────────────────────

function TouchpointDetailPanel({ tpId, onClose }: { tpId: string; onClose: () => void }) {
  const tp = TOUCHPOINTS.find(t => t.id === tpId);
  if (!tp) return null;
  const agent = tp.agentId ? getAgent(tp.agentId) : null;
  const layer = getLayer(tp.layerId);

  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: 20 }}
      className="bg-white border border-border rounded-xl shadow-lg p-5 w-80 shrink-0 self-start sticky top-0"
    >
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <div className={`w-8 h-8 rounded-full ${layer?.color || "bg-slate-500"} flex items-center justify-center text-white text-xs font-bold`}>
            {tp.id}
          </div>
          <div>
            <div className="text-sm font-bold text-foreground">{tp.id}</div>
            <div className="text-xs text-muted-foreground">{tp.name}</div>
          </div>
        </div>
        <button onClick={onClose} className="text-muted-foreground hover:text-foreground">
          <X className="w-4 h-4" />
        </button>
      </div>

      <div className="space-y-3 text-xs">
        <Row label="System Owner" value={tp.system} />
        <Row label="Platform Layer" value={layer?.label || ""} sub={layer?.authority} />
        <Row label="Executing Agent" value={agent?.name || "Practitioner / Manual"} sub={agent?.role} />
        <Row label="Gate" value={tp.gate} />
        <Row label="Authority Action" value={tp.isAuthorityAction ? "Yes — establishes platform authority" : "No"} />

        <div>
          <div className="font-semibold uppercase tracking-wider text-muted-foreground mb-1">Responsibility</div>
          <p className="text-muted-foreground leading-relaxed">{tp.responsibility}</p>
        </div>

        <div>
          <div className="font-semibold uppercase tracking-wider text-muted-foreground mb-1">Inputs</div>
          <div className="space-y-0.5">
            {tp.inputs.map((inp, i) => (
              <div key={i} className="text-muted-foreground flex items-start gap-1">
                <ArrowRight className="w-3 h-3 text-[#003A8F] shrink-0 mt-0.5" />{inp}
              </div>
            ))}
          </div>
        </div>

        <div>
          <div className="font-semibold uppercase tracking-wider text-muted-foreground mb-1">Outputs</div>
          <div className="space-y-0.5">
            {tp.outputs.map((out, i) => (
              <div key={i} className="text-muted-foreground flex items-start gap-1">
                <CheckCircle2 className="w-3 h-3 text-emerald-500 shrink-0 mt-0.5" />{out}
              </div>
            ))}
          </div>
        </div>
      </div>
    </motion.div>
  );
}

function Row({ label, value, sub }: { label: string; value: string; sub?: string }) {
  return (
    <div>
      <div className="font-semibold uppercase tracking-wider text-muted-foreground">{label}</div>
      <div className="font-medium text-foreground mt-0.5">{value}</div>
      {sub && <div className="text-muted-foreground">{sub}</div>}
    </div>
  );
}

// ─── ARCHITECTURE RULES ───────────────────────────────────────────────────────

function ArchitectureRules() {
  return (
    <div className="bg-[#003A8F] rounded-xl p-5 text-white">
      <div className="text-xs font-bold uppercase tracking-widest text-blue-200 mb-3">Architecture Rules — Enforced</div>
      <div className="grid grid-cols-2 gap-3">
        {[
          { icon: Brain, rule: "AI Orchestrator (Roger AI) = Stateless Compute", sub: "Performs T2, T3, T8 — never system of record" },
          { icon: Database, rule: "PDC = Canonical Financial Authority", sub: "All financial data authority flows through PDC" },
          { icon: Shield, rule: "TDC = Tax Decision Authority", sub: "All tax decisions persisted immutably in TDC" },
          { icon: CheckCircle2, rule: "Roger UI = Read-Only Consumer", sub: "Surfaces data only — no write operations" },
        ].map((r, i) => (
          <div key={i} className="flex items-start gap-2">
            <r.icon className="w-4 h-4 text-blue-300 shrink-0 mt-0.5" />
            <div>
              <div className="text-xs font-semibold text-white">{r.rule}</div>
              <div className="text-xs text-blue-200/80">{r.sub}</div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ─── VISIO DIAGRAM TAB ────────────────────────────────────────────────────────

const PLATFORM_ARCH_CDN_URL = "https://d2xsxph8kpxj0f.cloudfront.net/310519663402976610/6z8sjWGC7ihkVcDSZGqeBn/DCT_Platform_Architecture_v1_3176731c.png";

// ─── ZOOM PAN VIEWER (used only for Full Platform Architecture tab) ───────────

function ZoomPanViewer({ src, alt }: { src: string; alt: string }) {
  const BASE_WIDTH = 2600;
  const STEP = 400;
  const MIN_W = 1200;
  const MAX_W = 6000;
  const [imageWidth, setImageWidth] = useState(BASE_WIDTH);
  const [fullscreen, setFullscreen] = useState(false);
  const clampW = (w: number) => Math.min(MAX_W, Math.max(MIN_W, w));
  const zoomIn  = () => setImageWidth(w => clampW(w + STEP));
  const zoomOut = () => setImageWidth(w => clampW(w - STEP));
  const reset   = () => setImageWidth(BASE_WIDTH);
  const pct = Math.round((imageWidth / BASE_WIDTH) * 100);

  return (
    <>
      <div className="bg-white border border-border rounded-xl overflow-hidden shadow-sm">
        <div className="bg-[#003A8F] px-4 py-2.5 flex items-center justify-between gap-2">
          <span className="text-xs font-semibold text-white truncate">DCT Platform — Full Stack Architecture</span>
          <div className="flex items-center gap-2 shrink-0">
            <span className="text-xs text-blue-200 font-mono tabular-nums w-12 text-right">{pct}%</span>
            <button onClick={zoomOut} title="Zoom out" className="w-7 h-7 rounded flex items-center justify-center hover:bg-white/20 text-white transition-colors text-base font-bold">−</button>
            <button onClick={reset} title="Reset" className="px-2.5 py-1 rounded text-xs font-bold hover:bg-white/20 text-white border border-white/40 transition-colors">Reset</button>
            <button onClick={zoomIn} title="Zoom in" className="w-7 h-7 rounded flex items-center justify-center hover:bg-white/20 text-white transition-colors text-base font-bold">+</button>
            <div className="w-px h-4 bg-white/30 mx-1" />
            <button onClick={() => setFullscreen(true)} title="Full screen" className="w-7 h-7 rounded flex items-center justify-center hover:bg-white/20 text-white transition-colors"><Maximize2 className="w-3.5 h-3.5" /></button>
            <a href={src} download="DCT_Platform_Architecture.png" target="_blank" rel="noopener noreferrer" title="Download PNG" className="w-7 h-7 rounded flex items-center justify-center hover:bg-white/20 text-white transition-colors"><Download className="w-3.5 h-3.5" /></a>
          </div>
        </div>
        <div className="bg-slate-50 border-b border-border px-4 py-1.5 flex items-center gap-2">
          <Move className="w-3 h-3 text-muted-foreground shrink-0" />
          <span className="text-xs text-muted-foreground">Scroll to navigate · Use + / − to resize · Reset returns to default width · Full screen for presentations</span>
        </div>
        <div className="overflow-auto bg-[#f0f2f5]" style={{ height: "700px" }}>
          <img src={src} alt={alt} draggable={false} style={{ width: imageWidth, height: "auto", display: "block", userSelect: "none" }} />
        </div>
        <div className="bg-slate-50 border-t border-border px-4 py-2 flex items-center justify-between">
          <span className="text-xs text-muted-foreground">Source: {ARCH_METADATA.sourceOfTruth} · {ARCH_METADATA.layerCount} swimlanes · {ARCH_METADATA.touchpointCount} touchpoints</span>
          <button onClick={() => setFullscreen(true)} className="text-xs text-[#003A8F] font-semibold hover:underline flex items-center gap-1">
            <Maximize2 className="w-3 h-3" /> Open full screen
          </button>
        </div>
      </div>
      <AnimatePresence>
        {fullscreen && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 bg-[#0a1628] flex flex-col">
            <div className="bg-[#003A8F] px-4 py-2.5 flex items-center justify-between gap-2">
              <span className="text-xs font-semibold text-white truncate">DCT Platform — Full Stack Architecture</span>
              <div className="flex items-center gap-2 shrink-0">
                <span className="text-xs text-blue-200 font-mono tabular-nums w-12 text-right">{pct}%</span>
                <button onClick={zoomOut} className="w-7 h-7 rounded flex items-center justify-center hover:bg-white/20 text-white transition-colors text-base font-bold">−</button>
                <button onClick={reset} className="px-2.5 py-1 rounded text-xs font-bold hover:bg-white/20 text-white border border-white/40 transition-colors">Reset</button>
                <button onClick={zoomIn} className="w-7 h-7 rounded flex items-center justify-center hover:bg-white/20 text-white transition-colors text-base font-bold">+</button>
                <div className="w-px h-4 bg-white/30 mx-1" />
                <button onClick={() => setFullscreen(false)} className="w-7 h-7 rounded flex items-center justify-center hover:bg-white/20 text-white transition-colors"><X className="w-3.5 h-3.5" /></button>
              </div>
            </div>
            <div className="flex-1 overflow-auto bg-[#f0f2f5]">
              <img src={src} alt={alt} draggable={false} style={{ width: imageWidth, height: "auto", display: "block", userSelect: "none" }} />
            </div>
            <div className="bg-[#0F2A5C] px-4 py-2 text-xs text-blue-300 text-center">
              RSM | CATT · DCT Platform Full Stack Architecture · Click × to close
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}

// ─── SWIMLANE PROCESS FLOW DATA ───────────────────────────────────────────────

const SWIMLANE_LAYERS = [
  {
    num: 1,
    title: "Platform Entry & Ingestion",
    owner: "Platform",
    desc: "All entry points converge into Tax Portal, which enforces the ingestion contract and publishes the event to the Service Bus",
    color: "bg-slate-700",
    borderColor: "border-slate-500",
    entryPoints: ["Direct Upload", "Roger Web App", "Phoenix (future)", "Duo / DSDMS (transition)"],
    touchpointId: "T1",
    touchpointLabel: "TAX PORTAL",
    touchpointSub: "Owner: Platform · Single ingestion gate",
    sections: [
      {
        title: "Ingestion Gate",
        owner: "Owner: Platform",
        items: [
          "Generate DocumentId (GUID) — immutable",
          "Generate JobId (GUID)",
          "Validate ClientId (GUID) — REQUIRED",
          "Validate EntityId (GUID) — REQUIRED",
          "Validate PeriodStart + PeriodEnd — REQUIRED",
          "Enforce: PeriodEnd >= PeriodStart",
          "Document registration",
          "Publish NEW_FILE_EVENT",
        ],
      },
      {
        title: "NEW_FILE_EVENT Contract",
        owner: "",
        items: [
          "ClientId: GUID — REQUIRED",
          "EntityId: GUID — REQUIRED",
          "DocumentId: GUID (immutable)",
          "JobId: GUID",
          "PeriodStart: DateOnly — REQUIRED",
          "PeriodEnd: DateOnly — REQUIRED",
          "DocumentType: enum",
          "Timestamp: datetime",
          "SourceSystem: string",
          "RequestedBy: string",
          "Note: TaxYear NOT in payload",
        ],
      },
    ],
    annotation: "Tax Portal enforces ingestion contract across all entry points.",
    flowLabel: "NEW_FILE_EVENT → Service Bus",
    serviceBus: {
      label: "SERVICE BUS",
      sub: "Owner: Platform · Event handoff only",
      tpId: "T2",
      items: [
        "Topic: file_ingestion_events",
        "Consumer: PDC Ingestion Listener",
        "Payload: NEW_FILE_EVENT (no mutation)",
        "Delivery: at-least-once",
        "Replay supported",
      ],
      annotation: "Service Bus is transport only — no processing or enrichment.",
      warning: "No other systems use the Service Bus. Tax Portal → PDC event handoff only.",
      flowLabel: "NEW_FILE_EVENT → PDC Listener",
    },
  },
  {
    num: 2,
    title: "PDC Receives Event & Persists Initial Record",
    owner: "DCT",
    desc: "PDC listens on the Service Bus for new file events. Upon receipt PDC immediately persists the ingestion record.",
    color: "bg-emerald-700",
    borderColor: "border-emerald-500",
    touchpointId: null,
    touchpointLabel: "PDC — Phoenix Data Consolidation · Cross-LOB System of Record · Ingestion Persistence",
    touchpointSub: "",
    sections: [
      {
        title: "PDC Ingestion Listener",
        owner: "",
        items: [
          "PDC listens on the Service Bus for new file events",
          "Upon receipt PDC immediately persists: ClientId, EntityId, DocumentId, JobId, PeriodStart, PeriodEnd, file metadata",
          "TaxYear is NOT stored in PDC — it is derived in TDC from PeriodStart",
          "PDC sets initial record state: INGESTED",
        ],
      },
      {
        title: "IngestionJob",
        owner: "Owner: DCT",
        items: [
          "JobId (GUID) — PRIMARY tracking key",
          "ClientId (GUID) — REQUIRED",
          "EntityId (GUID) — REQUIRED",
          "PeriodStart (DateOnly) — REQUIRED",
          "PeriodEnd (DateOnly) — REQUIRED",
          "Status enum = INGESTED",
          "CreatedTimestamp · RequestedBy · SourceSystem",
          "Rule: TaxYear NOT stored — derived in TDC only",
        ],
      },
      {
        title: "SourceFile",
        owner: "",
        items: [
          "SourceFileId (GUID) — record key",
          "DocumentId (GUID) — immutable lineage anchor",
          "JobId FK (GUID) — links to IngestionJob",
          "FileName · FileType · UploadTimestamp",
          "DocumentType (enum)",
        ],
      },
    ],
    annotation: "Audit record exists before AI is invoked.",
    flowLabel: "PDC advances state to PROCESSING · prepares invocation payload",
    stateMachine: ["INGESTED", "PROCESSING", "READY"],
    api: "GET /api/pdc/ingestion/status?jobId={JobId}",
  },
  {
    num: 3,
    title: "PDC → AI Orchestrator (Single Invocation)",
    owner: "DCT (trigger) · Roger Team (execution)",
    desc: "PDC advances the record state to PROCESSING and invokes the AI Orchestrator. This is the only AI invocation for this file.",
    color: "bg-blue-700",
    borderColor: "border-blue-500",
    touchpointId: "T3",
    touchpointLabel: "ORCHESTRATOR INVOCATION",
    touchpointSub: "",
    sections: [
      {
        title: "Invocation Payload",
        owner: "",
        items: [
          "ClientId (GUID) — REQUIRED",
          "EntityId (GUID) — REQUIRED",
          "DocumentId (GUID)",
          "JobId (GUID)",
          "PeriodStart (DateOnly) — REQUIRED",
          "PeriodEnd (DateOnly) — REQUIRED",
          "file metadata",
          "TaxYear is NOT passed — PeriodStart/PeriodEnd are the temporal model",
        ],
      },
    ],
    annotation: "The AI Orchestrator is stateless — it does not persist data. All persistence occurs through PDC or TDC APIs.",
    warning: "PDC and TDC never communicate directly. All coordination flows through the Orchestrator.",
    flowLabel: "Single invocation per file · ClientId + EntityId + DocumentId + PeriodStart + PeriodEnd + file_metadata",
  },
  {
    num: 4,
    title: "AI Orchestrator",
    owner: "Roger Team · Stateless compute layer",
    desc: "Three-stage agent pipeline: File Recognition & Normalization → Cross-LOB Taxonomy (PDC) → Tax Taxonomy (TDC)",
    color: "bg-blue-600",
    borderColor: "border-blue-400",
    touchpointId: "T4",
    touchpointLabel: "STAGE 1 — File Recognition & Normalization (File Level)",
    touchpointSub: "",
    stages: [
      {
        tpId: "T4",
        label: "STAGE 1 — File Recognition & Normalization (File Level)",
        agents: [
          { name: "Agent 1 — File Recognizer", items: ["Pattern-matches incoming file structure against canonical schemas", "Pulls canonical schemas from PDC API (read-only)", "Identifies document type (e.g., Trial Balance, K-1, W-2, 1099)"] },
          { name: "Agent 2 — File Normalizer", items: ["Extracts raw data and transforms it into the standard canonical format", "Pulls canonical schemas from PDC API (read-only)"] },
        ],
        output: "Normalized canonical records",
        api: "PDC API",
      },
      {
        tpId: "T5",
        label: "STAGE 2 — Cross-LOB Taxonomy (PDC) (Record Level)",
        agents: [
          { name: "Agent 3 — Cross-LOB / Firm Taxonomy Mapper", items: ["Maps each normalized account record independently to the firm's financial taxonomy", "Categories: asset, liability, equity, income, expense", "Pulls firm and cross-LOB taxonomy tables from PDC API (read-only)"] },
        ],
        output: "RunId (GUID) · SourceRecordId (GUID) · READY state",
        api: "TDC API",
        note: "PDC is the authoritative cross-LOB system of record. Stage 3 cannot begin until source_record_id is returned.",
      },
      {
        tpId: "T6",
        label: "STAGE 3 — Tax Taxonomy (TDC) (Record Level)",
        agents: [
          { name: "Agent 4 — Tax Taxonomy Mapper", items: ["Maps each cross-LOB mapped account record independently to the tax taxonomy", "Pulls tax taxonomy tables and rules from TDC API (read-only)", "Produces proposed tax line, confidence band (GREEN / YELLOW / RED), and evidence / reasoning"] },
        ],
        output: "TdcRecordId (GUID) · ConfidenceBand (GREEN|YELLOW|RED) · tax mapping proposals",
        api: "",
        warning: "Agents never persist data directly. All results are written through PDC or TDC APIs.",
      },
    ],
    flowLabel: "Roger Query API (read-only) · GET /api/tdc/records",
  },
  {
    num: 5,
    title: "Roger Web Application",
    owner: "Roger Team · UI layer only · Read-only consumer of TDC",
    desc: "Roger retrieves tax records via TDC API. Practitioner reviews AI-generated tax mapping proposals.",
    color: "bg-pink-700",
    borderColor: "border-pink-500",
    touchpointId: "T7",
    touchpointLabel: "ROGER WEB APP",
    touchpointSub: "Owner: Roger Team",
    sections: [
      {
        title: "Roger Web App",
        owner: "Owner: Roger Team",
        items: [
          "Tax mapping review",
          "Confidence score display",
          "Approve / Correct / Override",
          "Lineage trace view",
          "GET /api/tdc/records?entityId={guid}&periodStart={date}&periodEnd={date}",
          "GET /api/tdc/records/{tdcRecordId}/lineage",
          "Note: No TaxYear param — scoped by ClientId + EntityId + PeriodStart + PeriodEnd",
        ],
      },
    ],
    annotation: "Roger never: Runs AI · Mutates PDC · Mutates TDC · Bypasses APIs.",
    flowLabel: "Practitioner actions (dashed = user interaction)",
  },
  {
    num: 6,
    title: "User Review & Adjustment (Human-in-the-loop)",
    owner: "Practitioner (via Roger UI)",
    desc: "Practitioner approves, corrects, or overrides AI-generated tax mapping proposals.",
    color: "bg-orange-700",
    borderColor: "border-orange-500",
    touchpointId: "T8",
    touchpointLabel: "PRACTITIONER ACTIONS",
    touchpointSub: "",
    sections: [
      {
        title: "Practitioner Actions",
        owner: "",
        items: [
          "Approve tax mappings",
          "Correct mapping errors",
          "Reclassify accounts (e.g. liability → asset)",
          "Override tax line assignments",
        ],
      },
      {
        title: "Adjustment Routing (Append-Only)",
        owner: "",
        items: [
          "Cross-LOB meaning change → PDC (new FinancialFact version, GUID)",
          "Tax classification change → TDC (new MappingDecision appended)",
          "Both → PDC first, then TDC",
          "Lifecycle: Draft → Submitted → Approved → Applied → Locked",
          "No overwrites — append-only. Locked records are immutable.",
        ],
      },
    ],
    annotation: "Adjustment routed to PDC and/or TDC via API",
    flowLabel: "Adjustment routed to PDC and/or TDC via API",
  },
  {
    num: 7,
    title: "Adjustment Propagation",
    owner: "DCT · Corrections routed based on the nature of the change",
    desc: "Corrections are routed to PDC, TDC, or both depending on whether the change is cross-LOB or tax-only.",
    color: "bg-red-700",
    borderColor: "border-red-500",
    touchpointId: "T9",
    touchpointLabel: "CORRECTION TYPES",
    touchpointSub: "",
    sections: [
      {
        title: "Correction Types & Routing",
        owner: "",
        items: [
          "Cross-LOB meaning changed → PDC: new FinancialFact version (GUID)",
          "Tax meaning only → TDC: new MappingDecision appended (GUID)",
          "Both → PDC first (FinancialFact), then TDC (MappingDecision)",
          "LineageEvent appended with EventType=CORRECTION on each change",
          "All downstream systems stay consistent regardless of the correction path",
        ],
      },
    ],
    annotation: "Final state assignment → TDC",
    flowLabel: "Final state assignment → TDC",
  },
  {
    num: 8,
    title: "TDC Finalization",
    owner: "DCT · Authoritative tax record finalization and versioning",
    desc: "TDC assigns the final record state. Tax truth is finalized here.",
    color: "bg-red-800",
    borderColor: "border-red-600",
    touchpointId: "T10",
    touchpointLabel: "TDC FINAL STATE ASSIGNMENT",
    touchpointSub: "",
    sections: [
      {
        title: "TDC Final State Assignment",
        owner: "",
        items: [
          "REVIEW_REQUIRED — After AI proposal, practitioner action required",
          "TAX_READY — After practitioner approval and sign-off",
          "TDC versions all decisions",
          "All final tax outcomes are stored as authoritative records",
          "Tax truth is finalized here",
        ],
      },
    ],
    annotation: "PDC READY signal · TDC TAX_READY record",
    flowLabel: "Downstream Consumption",
  },
];

const LINEAGE_CHAIN = [
  { id: "DocumentId (GUID)", system: "Tax Portal", note: "Immutable · Lineage anchor" },
  { id: "JobId (GUID)", system: "Tax Portal", note: "Assigned at ingestion" },
  { id: "SourceRecordId (GUID)", system: "PDC", note: "GUID · Normalization" },
  { id: "RunId (GUID)", system: "PDC", note: "Batch traceability" },
  { id: "TdcRecordId (GUID)", system: "TDC", note: "GUID · Tax Record" },
  { id: "FilingId (GUID)", system: "TDC / Roger", note: "Immutable · Filed return" },
];

const TOUCHPOINT_LEGEND = [
  { id: "T1", name: "File Ingestion via Tax Portal", step: "Step 1", batch: "Batch 1", system: "Tax Portal", desc: "Tax Portal generates DocumentId (GUID) + JobId (GUID), validates EntityId + PeriodStart + PeriodEnd, publishes NEW_FILE_EVENT." },
  { id: "T2", name: "PDC Record Creation", step: "Step 2", batch: "Batch 1", system: "PDC", desc: "PDC persists IngestionJob + SourceFile. Status enum = INGESTED. Service Bus is transport only." },
  { id: "T3", name: "AI Processing Trigger", step: "Step 3", batch: "Batch 2", system: "PDC → AI Orchestrator", desc: "PDC advances record state to PROCESSING and invokes the AI Orchestrator once per file." },
  { id: "T4", name: "AI Agent Pipeline Execution", step: "Step 4", batch: "Batch 2", system: "AI Orchestrator", desc: "Agent chain: File Recognizer → File Normalizer → Cross-LOB Mapper → Tax Mapper. Stateless agents persist via APIs." },
  { id: "T5", name: "Canonical Dataset Persistence", step: "Step 4", batch: "Batch 2", system: "PDC", desc: "PDC persists normalized FinancialFact records + Cross-LOB mappings. Assigns RunId + SourceRecordId. Status = READY." },
  { id: "T6", name: "Tax Record Creation in TDC", step: "Step 4", batch: "Batch 3", system: "TDC", desc: "Tax mapping proposals stored in TDC. TDC assigns tdc_record_id and preserves full lineage." },
  { id: "T7", name: "Practitioner View in Roger", step: "Step 5", batch: "Batch 4", system: "Roger Web App", desc: "Roger retrieves tax records via GET /api/tdc/records. Read-only consumer of TDC." },
  { id: "T8", name: "Practitioner Decision", step: "Step 6", batch: "Batch 5", system: "Roger Web App", desc: "Practitioner approves, corrects, overrides, or reclassifies mappings. Decision captured against tdc_record_id." },
  { id: "T9", name: "Adjustment Propagation", step: "Step 7", batch: "Batch 5", system: "DCT (PDC + TDC APIs)", desc: "Corrections routed via API: Cross-LOB → PDC, Tax classification → TDC, Both → PDC then TDC." },
  { id: "T10", name: "TDC Finalization — TAX_READY", step: "Step 8", batch: "Batch 5", system: "TDC", desc: "TDC assigns final state: REVIEW_REQUIRED or TAX_READY. All tax decisions versioned as authoritative output." },
];

function VisioDiagramTab() {
  const [expandedLayer, setExpandedLayer] = useState<number | null>(null);
  const [selectedTpLegend, setSelectedTpLegend] = useState<string | null>(null);

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="bg-white border border-border rounded-xl px-5 py-4">
        <div className="text-xs font-bold uppercase tracking-widest text-muted-foreground mb-1">RSM CATT · DCT PLATFORM · ARCHITECTURE REVIEW DOCUMENT</div>
        <h2 className="text-xl font-bold text-foreground">DCT Platform Architecture — End-to-End Flow for Roger Platform</h2>
        <div className="text-xs text-muted-foreground mt-1">Baseline v1.0 &nbsp;|&nbsp; Owner: DCT &nbsp;|&nbsp; Agentic Execution Model</div>
        <div className="mt-3 flex flex-wrap gap-2">
          <span className="inline-flex items-center gap-1.5 text-xs bg-[#003A8F] text-white px-3 py-1.5 rounded-lg font-semibold"><Play className="w-3 h-3" />Executive Demo</span>
          <span className="inline-flex items-center gap-1.5 text-xs bg-white border border-border text-muted-foreground px-3 py-1.5 rounded-lg font-medium"><Download className="w-3 h-3" />Export SVG</span>
          <span className="inline-flex items-center gap-1.5 text-xs bg-white border border-border text-muted-foreground px-3 py-1.5 rounded-lg font-medium"><Download className="w-3 h-3" />Export PNG</span>
        </div>
        <div className="mt-3 space-y-0.5">
          {["1. Tax Portal is the single ingestion gate.","2. AI Orchestrator runs once.","3. PDC owns cross-LOB truth.","4. TDC owns tax truth.","5. Roger reads and surfaces practitioner decisions."].map((g,i) => (
            <div key={i} className="text-xs text-muted-foreground">{g}</div>
          ))}
        </div>
      </div>

      {/* Swimlane layers */}
      <div className="space-y-3">
        {SWIMLANE_LAYERS.map((layer) => (
          <div key={layer.num} className={`rounded-xl border-2 ${layer.borderColor} overflow-hidden`}>
            {/* Layer header */}
            <button
              className={`w-full flex items-start gap-3 px-5 py-3 ${layer.color} text-white text-left hover:opacity-95 transition-opacity`}
              onClick={() => setExpandedLayer(expandedLayer === layer.num ? null : layer.num)}
            >
              <div className="w-7 h-7 rounded-full bg-white/20 flex items-center justify-center text-sm font-bold shrink-0 mt-0.5">{layer.num}</div>
              <div className="flex-1">
                <div className="font-bold text-sm uppercase tracking-wide">{layer.title}</div>
                <div className="text-xs text-white/80 mt-0.5">Owner: {layer.owner}</div>
                <div className="text-xs text-white/70 mt-0.5">{layer.desc}</div>
              </div>
              {layer.touchpointId && (
                <span className="shrink-0 bg-white/20 border border-white/30 text-white text-xs font-bold px-2 py-0.5 rounded-full mt-1">{layer.touchpointId}</span>
              )}
              <span className="text-white/60 text-xs mt-1">{expandedLayer === layer.num ? "▲" : "▼"}</span>
            </button>

            {/* Layer body */}
            {expandedLayer === layer.num && (
              <div className="bg-white px-5 py-4 space-y-4">
                {/* Entry points for layer 1 */}
                {layer.entryPoints && (
                  <div>
                    <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-2">Entry Points</div>
                    <div className="flex flex-wrap gap-2 items-center">
                      {layer.entryPoints.map((ep) => (
                        <span key={ep} className="text-xs border border-border rounded-lg px-3 py-1.5 text-foreground bg-slate-50">{ep}</span>
                      ))}
                      <span className="text-xs text-muted-foreground">→ converge →</span>
                      <span className="text-xs bg-[#003A8F] text-white rounded-lg px-3 py-1.5 font-semibold">Tax Portal</span>
                    </div>
                    <div className="text-xs text-muted-foreground mt-1">All entry points → Tax Portal</div>
                  </div>
                )}

                {/* Touchpoint label */}
                {layer.touchpointLabel && (
                  <div className="flex items-center gap-2">
                    <div className="text-xs font-bold uppercase tracking-wider text-foreground">{layer.touchpointLabel}</div>
                    {layer.touchpointId && <span className="bg-[#003A8F] text-white text-xs font-bold px-2 py-0.5 rounded-full">{layer.touchpointId}</span>}
                    {layer.touchpointSub && <span className="text-xs text-muted-foreground">{layer.touchpointSub}</span>}
                  </div>
                )}

                {/* Sections */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {layer.sections?.map((sec) => (
                    <div key={sec.title} className="bg-slate-50 border border-border rounded-lg p-3">
                      <div className="text-xs font-bold text-foreground mb-1">{sec.title}</div>
                      {sec.owner && <div className="text-xs text-[#003A8F] font-semibold mb-1">{sec.owner}</div>}
                      <ul className="space-y-0.5">
                        {sec.items.map((item, i) => (
                          <li key={i} className="text-xs text-muted-foreground flex items-start gap-1.5">
                            <span className="text-[#003A8F] shrink-0 mt-0.5">•</span>{item}
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>

                {/* Stages (layer 4) */}
                {layer.stages?.map((stage) => (
                  <div key={stage.tpId} className="bg-blue-50 border border-blue-200 rounded-lg p-3">
                    <div className="flex items-center gap-2 mb-2">
                      <span className="bg-blue-700 text-white text-xs font-bold px-2 py-0.5 rounded-full">{stage.tpId}</span>
                      <div className="text-xs font-bold text-blue-900">{stage.label}</div>
                    </div>
                    {stage.agents.map((agent) => (
                      <div key={agent.name} className="mb-2">
                        <div className="text-xs font-semibold text-blue-800 mb-1">{agent.name}</div>
                        <ul className="space-y-0.5">
                          {agent.items.map((item, i) => (
                            <li key={i} className="text-xs text-blue-700 flex items-start gap-1.5"><span className="shrink-0">•</span>{item}</li>
                          ))}
                        </ul>
                      </div>
                    ))}
                    {stage.output && <div className="text-xs text-emerald-700 font-medium mt-1">Output: {stage.output}</div>}
                    {stage.note && <div className="text-xs text-amber-700 mt-1 italic">{stage.note}</div>}
                    {stage.warning && <div className="text-xs text-red-700 mt-1 font-medium">⚠ {stage.warning}</div>}
                  </div>
                ))}

                {/* State machine */}
                {layer.stateMachine && (
                  <div className="flex items-center gap-2">
                    <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">State Machine:</div>
                    {layer.stateMachine.map((s, i) => (
                      <span key={s}>
                        <span className="text-xs bg-emerald-100 text-emerald-800 border border-emerald-300 px-2 py-0.5 rounded font-bold">{s}</span>
                        {i < layer.stateMachine!.length - 1 && <span className="text-muted-foreground mx-1">→</span>}
                      </span>
                    ))}
                  </div>
                )}

                {/* API */}
                {layer.api && (
                  <div className="bg-slate-100 rounded px-3 py-2">
                    <div className="text-xs font-semibold text-muted-foreground mb-0.5">API</div>
                    <code className="text-xs text-[#003A8F] font-mono">{layer.api}</code>
                  </div>
                )}

                {/* Annotation */}
                {layer.annotation && (
                  <div className="bg-amber-50 border border-amber-200 rounded-lg px-3 py-2">
                    <span className="text-xs font-semibold text-amber-800">Annotation: </span>
                    <span className="text-xs text-amber-700">{layer.annotation}</span>
                  </div>
                )}

                {/* Warning */}
                {layer.warning && (
                  <div className="bg-red-50 border border-red-200 rounded-lg px-3 py-2 flex items-start gap-2">
                    <span className="text-red-500 shrink-0">⚠</span>
                    <span className="text-xs text-red-700">{layer.warning}</span>
                  </div>
                )}

                {/* Service Bus sub-section (layer 1) */}
                {layer.serviceBus && (
                  <div className="border-t border-border pt-3 space-y-3">
                    <div className="flex items-center gap-2">
                      <div className="text-xs font-bold uppercase tracking-wider text-foreground">{layer.serviceBus.label}</div>
                      <span className="bg-slate-600 text-white text-xs font-bold px-2 py-0.5 rounded-full">{layer.serviceBus.tpId}</span>
                      <span className="text-xs text-muted-foreground">{layer.serviceBus.sub}</span>
                    </div>
                    <div className="bg-slate-50 border border-border rounded-lg p-3">
                      <ul className="space-y-0.5">
                        {layer.serviceBus.items.map((item, i) => (
                          <li key={i} className="text-xs text-muted-foreground flex items-start gap-1.5"><span className="text-slate-500 shrink-0">•</span>{item}</li>
                        ))}
                      </ul>
                    </div>
                    <div className="bg-amber-50 border border-amber-200 rounded-lg px-3 py-2">
                      <span className="text-xs font-semibold text-amber-800">Annotation: </span>
                      <span className="text-xs text-amber-700">{layer.serviceBus.annotation}</span>
                    </div>
                    <div className="bg-red-50 border border-red-200 rounded-lg px-3 py-2 flex items-start gap-2">
                      <span className="text-red-500 shrink-0">⚠</span>
                      <span className="text-xs text-red-700">{layer.serviceBus.warning}</span>
                    </div>
                  </div>
                )}

                {/* Flow label */}
                <div className="flex items-center gap-2 text-xs text-muted-foreground border-t border-border pt-2">
                  <ArrowDown className="w-3 h-3 shrink-0" />
                  <span>{layer.flowLabel}</span>
                </div>
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Downstream Consumption */}
      <div className="bg-white border border-border rounded-xl p-4">
        <div className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-2">Downstream Consumption — Platform Extensibility</div>
        <div className="text-xs text-muted-foreground mb-3">Any domain can subscribe to PDC and TDC outputs — no changes are required to PDC or TDC as new domains come online.</div>
        <div className="grid grid-cols-2 gap-2">
          {[
            { signal: "PDC READY", avail: "Tax · Audit · Consulting · any future LOB", color: "bg-emerald-50 border-emerald-200 text-emerald-800" },
            { signal: "TDC TAX_READY", avail: "Tax preparation · filing · reporting systems", color: "bg-red-50 border-red-200 text-red-800" },
          ].map(d => (
            <div key={d.signal} className={`border rounded-lg px-3 py-2 ${d.color}`}>
              <div className="text-xs font-bold">{d.signal}</div>
              <div className="text-xs opacity-80 mt-0.5">{d.avail}</div>
            </div>
          ))}
        </div>
      </div>

      {/* End-to-End Audit Traceability */}
      <div className="bg-white border border-border rounded-xl p-4">
        <div className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-3">End-to-End Audit Traceability — Lineage Chain</div>
        <div className="flex flex-wrap items-center gap-2">
          {LINEAGE_CHAIN.map((item, i) => (
            <span key={item.id} className="flex items-center gap-2">
              <div className="bg-[#003A8F]/5 border border-[#003A8F]/20 rounded-lg px-3 py-2 text-center">
                <div className="text-xs font-bold text-[#003A8F]">{item.id}</div>
                <div className="text-xs text-muted-foreground">{item.system}</div>
                <div className="text-xs text-slate-400 italic">{item.note}</div>
              </div>
              {i < LINEAGE_CHAIN.length - 1 && <ArrowRight className="w-3 h-3 text-muted-foreground shrink-0" />}
            </span>
          ))}
        </div>
      </div>

      {/* Touchpoint Legend */}
      <div className="bg-white border border-border rounded-xl p-4">
        <div className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-1">Touchpoint Legend — T1 – T10</div>
        <div className="text-xs text-muted-foreground mb-3">Click any row to see details · Source: TOUCHPOINTS model</div>
        <div className="overflow-x-auto">
          <table className="w-full text-xs">
            <thead>
              <tr className="border-b border-border">
                {["ID","Touchpoint Name","Step","Batch","System","Description"].map(h => (
                  <th key={h} className="text-left py-2 px-2 font-semibold uppercase tracking-wider text-muted-foreground">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {TOUCHPOINT_LEGEND.map((tp) => (
                <tr
                  key={tp.id}
                  onClick={() => setSelectedTpLegend(selectedTpLegend === tp.id ? null : tp.id)}
                  className={`border-b border-border cursor-pointer transition-colors ${
                    selectedTpLegend === tp.id ? "bg-[#003A8F]/5" : "hover:bg-slate-50"
                  }`}
                >
                  <td className="py-2 px-2"><span className="bg-[#003A8F] text-white font-bold px-1.5 py-0.5 rounded text-xs">{tp.id}</span></td>
                  <td className="py-2 px-2 font-medium text-foreground">{tp.name}</td>
                  <td className="py-2 px-2 text-muted-foreground">{tp.step}</td>
                  <td className="py-2 px-2 text-muted-foreground">{tp.batch}</td>
                  <td className="py-2 px-2 text-muted-foreground">{tp.system}</td>
                  <td className="py-2 px-2 text-muted-foreground max-w-xs">{selectedTpLegend === tp.id ? tp.desc : tp.desc.slice(0, 60) + "..."}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Legend */}
      <div className="bg-white border border-border rounded-xl p-4">
        <div className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-2">Legend</div>
        <div className="grid grid-cols-2 md:grid-cols-3 gap-2">
          {[
            { label: "Entry Points", owner: "Owner: —", color: "bg-slate-100 border-slate-300" },
            { label: "Platform Services", owner: "Owner: Platform", color: "bg-violet-100 border-violet-300" },
            { label: "PDC", owner: "Owner: DCT", color: "bg-emerald-100 border-emerald-300" },
            { label: "TDC", owner: "Owner: DCT", color: "bg-red-100 border-red-300" },
            { label: "AI Orchestrator", owner: "Owner: Roger Team", color: "bg-blue-100 border-blue-300" },
            { label: "Roger UI", owner: "Owner: Roger Team", color: "bg-pink-100 border-pink-300" },
          ].map(l => (
            <div key={l.label} className={`border rounded-lg px-3 py-2 ${l.color}`}>
              <div className="text-xs font-medium text-foreground">{l.label}</div>
              <div className="text-xs text-muted-foreground mt-0.5">{l.owner}</div>
            </div>
          ))}
        </div>
        <div className="mt-2 flex gap-4 text-xs text-muted-foreground">
          <span>→ Solid arrow — system / API flow</span>
          <span>⤳ Dashed arrow — user interaction</span>
          <span>⚠ Guardrail — architectural constraint</span>
        </div>
      </div>
    </div>
  );
}

// ─── MAIN PAGE ────────────────────────────────────────────────────────────────

export default function ArchitectureView() {
  const [selectedTp, setSelectedTp] = useState<string | null>(null);

  // Auto-activate tab from ?tab= query param (e.g. from Architecture Sync sidebar link)
  const getInitialTab = (): "visio" | "platform" | "interactive" | "adrs" | "openitems" | "dependencies" => {
    const params = new URLSearchParams(window.location.search);
    const t = params.get("tab");
    if (t === "platform" || t === "interactive" || t === "adrs" || t === "openitems" || t === "dependencies") return t;
    return "visio";
  };
  const [activeTab, setActiveTab] = useState<"visio" | "platform" | "interactive" | "adrs" | "openitems" | "dependencies">(getInitialTab);

  const tpsByLayer = (layerId: string) =>
    TOUCHPOINTS.filter(tp => tp.layerId === layerId);

  return (
    <div className="p-6 space-y-5">
      {/* Source of Truth Governance Notice */}
      <div className="bg-amber-50 border border-amber-200 rounded-xl px-4 py-3 flex items-start gap-3">
        <div className="w-5 h-5 rounded-full bg-amber-400 flex items-center justify-center shrink-0 mt-0.5">
          <Shield className="w-3 h-3 text-white" />
        </div>
        <div>
          <div className="text-xs font-bold text-amber-900">Visio Architecture is the Single Source of Truth</div>
          <div className="text-xs text-amber-800 mt-0.5">
            All platform representations — layers, touchpoints, agents, ADRs, open items, and dashboard visualizations — derive from the DCT Roger End-to-End Data Flow Visio diagram.
            If the Visio changes, the model and dashboard must update. No other artifact overrides the Visio architecture.
          </div>
        </div>
        <div className="flex items-center gap-2 shrink-0 ml-auto">
          <span className="text-xs bg-emerald-100 text-emerald-800 border border-emerald-200 px-2 py-0.5 rounded-full font-semibold">Synced</span>
          <span className="text-xs bg-[#003A8F]/10 text-[#003A8F] border border-[#003A8F]/20 px-2 py-0.5 rounded-full font-semibold">v{ARCH_METADATA.version}</span>
        </div>
      </div>

      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-lg font-bold text-foreground">Platform Architecture</h1>
          <p className="text-xs text-muted-foreground mt-0.5">
            {ARCH_METADATA.layerCount} layers · {ARCH_METADATA.touchpointCount} touchpoints · {ARCH_METADATA.agentCount} AI agents · {ARCH_METADATA.adrCount} ADRs · {ARCH_METADATA.openItemCount} open items
          </p>
        </div>
        <div className="flex items-center gap-2 flex-wrap">
          <span className="text-xs bg-[#003A8F]/10 text-[#003A8F] border border-[#003A8F]/20 px-2.5 py-1 rounded-full font-semibold">
            Source: {ARCH_METADATA.sourceOfTruth}
          </span>
          <span className="text-xs text-muted-foreground text-xs">{ARCH_METADATA.lastUpdated}</span>
        </div>
      </div>

      {/* Architecture Guardrails Banner */}
      <div className="bg-[#0F2A5C] rounded-xl px-5 py-3">
        <div className="flex items-center justify-between mb-2">
          <div className="text-xs font-bold uppercase tracking-widest text-blue-300">Architecture Guardrails — Non-Negotiable Platform Invariants</div>
          <span className="text-xs text-blue-400 font-medium">Defined by Visio · Enforced by all agents</span>
        </div>
        <div className="flex flex-wrap gap-x-6 gap-y-1">
          {ARCHITECTURE_GUARDRAILS.map(g => (
            <div key={g.id} className="flex items-center gap-1.5">
              <span className="text-xs font-bold text-blue-400">{g.id}</span>
              <span className="text-xs text-blue-100">{g.rule}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Tab switcher */}
      <div className="flex flex-wrap gap-1 bg-slate-100 rounded-xl p-1 w-fit">
        <button
          onClick={() => setActiveTab("visio")}
          className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-semibold transition-all ${
            activeTab === "visio"
              ? "bg-white text-[#003A8F] shadow-sm border border-border"
              : "text-muted-foreground hover:text-foreground"
          }`}
        >
          <Image className="w-3.5 h-3.5" />
          Visio Diagram
          <span className="text-xs bg-[#003A8F]/10 text-[#003A8F] px-1.5 py-0.5 rounded font-medium">Sync Agent</span>
        </button>
        <button
          onClick={() => setActiveTab("platform")}
          className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-semibold transition-all ${
            activeTab === "platform"
              ? "bg-white text-[#065F46] shadow-sm border border-border"
              : "text-muted-foreground hover:text-foreground"
          }`}
        >
          <Layers className="w-3.5 h-3.5" />
          Full Platform Architecture
          <span className="text-xs bg-green-100 text-green-800 px-1.5 py-0.5 rounded font-medium">B0–B10</span>
        </button>
        <button
          onClick={() => { setActiveTab("interactive"); setSelectedTp(null); }}
          className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-semibold transition-all ${
            activeTab === "interactive"
              ? "bg-white text-[#003A8F] shadow-sm border border-border"
              : "text-muted-foreground hover:text-foreground"
          }`}
        >
          <Layers className="w-3.5 h-3.5" />
          Interactive Swimlane
        </button>
        {(["adrs", "openitems", "dependencies"] as const).map(tab => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-semibold transition-all ${
              activeTab === tab
                ? "bg-white text-[#003A8F] shadow-sm border border-border"
                : "text-muted-foreground hover:text-foreground"
            }`}
          >
            {tab === "adrs" && <><Shield className="w-3.5 h-3.5" />ADRs <span className="text-xs bg-[#003A8F]/10 text-[#003A8F] px-1.5 py-0.5 rounded">{ARCH_METADATA.adrCount}</span></>}
            {tab === "openitems" && <><FileText className="w-3.5 h-3.5" />Open Items <span className="text-xs bg-amber-100 text-amber-800 px-1.5 py-0.5 rounded">{ARCH_METADATA.openItemCount}</span></>}
            {tab === "dependencies" && <><Link2 className="w-3.5 h-3.5" />Dependencies <span className="text-xs bg-red-100 text-red-800 px-1.5 py-0.5 rounded">{ARCH_METADATA.dependencyCount}</span></>}
          </button>
        ))}
      </div>

      {/* Tab content */}
      <AnimatePresence mode="wait">
        {activeTab === "visio" && (
          <motion.div key="visio" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}>
            <VisioDiagramTab />
          </motion.div>
        )}
        {activeTab === "platform" && (
          <motion.div key="platform" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}>
            <div className="space-y-4">
              <div className="grid grid-cols-3 gap-2">
                {[
                  { label: "PDC", sub: "Financial System of Record", color: "bg-emerald-50 border-emerald-300 text-emerald-800" },
                  { label: "TDC", sub: "Tax System of Record", color: "bg-orange-50 border-orange-300 text-orange-800" },
                  { label: "Roger", sub: "Read-Only Consumer · All via API Gateway", color: "bg-purple-50 border-purple-300 text-purple-800" },
                ].map(r => (
                  <div key={r.label} className={`border rounded-lg px-3 py-2 ${r.color}`}>
                    <div className="text-xs font-bold">{r.label}</div>
                    <div className="text-xs opacity-80">{r.sub}</div>
                  </div>
                ))}
              </div>
              <div className="rounded-2xl overflow-hidden border border-border bg-card">
                <div className="flex items-center justify-between px-4 py-3 bg-[#065F46] text-white">
                  <div>
                    <div className="font-semibold text-sm">DCT Platform — Full Stack Architecture · Batches 0–10</div>
                    <div className="text-xs text-green-200 mt-0.5">Roger · TDC · PDC · Service Bus · AI Orchestrator · API Gateway · Lineage</div>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-xs bg-green-800/60 text-green-200 px-2 py-0.5 rounded">v1.0 · 2026-03-12</span>
                    <a href={PLATFORM_ARCH_CDN_URL} download="DCT_Platform_Architecture_v1.png" target="_blank" rel="noopener noreferrer"
                      className="w-7 h-7 rounded flex items-center justify-center hover:bg-white/20 text-white transition-colors" title="Download PNG">
                      <Download className="w-3.5 h-3.5" />
                    </a>
                  </div>
                </div>
                <ZoomPanViewer src={PLATFORM_ARCH_CDN_URL} alt="DCT Platform Full Stack Architecture Batches 0-10" />
                <div className="px-4 py-2 bg-muted/30 border-t border-border flex items-center justify-between">
                  <div className="text-xs text-muted-foreground">DCT_Platform_Architecture_v1.png · Batch Roadmap B0–B10 · RSM | CATT · 2026-03-12</div>
                  <div className="flex gap-3 text-xs">
                    <span className="text-green-700 font-medium">PDC — Financial System of Record</span>
                    <span className="text-orange-700 font-medium">TDC — Tax System of Record</span>
                    <span className="text-purple-700 font-medium">Roger — Read-Only Consumer</span>
                  </div>
                </div>
              </div>
            </div>
          </motion.div>
        )}
        {activeTab === "interactive" && (
          <motion.div key="interactive" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}>
            <div className="flex gap-5 items-start">
              <div className="flex-1 space-y-2">
                <div className="bg-slate-900 rounded-2xl p-4 space-y-2">
                  <div className="text-xs font-semibold uppercase tracking-widest text-slate-400 mb-3 px-1">
                    DCT Platform Architecture Stack — T1–T11 Runtime Flow · Click any touchpoint for detail
                  </div>
                  {PLATFORM_LAYERS.map((layer, i) => (
                    <div key={layer.id}>
                      <LayerRow layer={layer} touchpoints={tpsByLayer(layer.id)} selectedTp={selectedTp} onSelectTp={setSelectedTp} />
                      {i < PLATFORM_LAYERS.length - 1 && (
                        <div className="flex justify-center py-1"><ArrowDown className="w-4 h-4 text-slate-500" /></div>
                      )}
                    </div>
                  ))}
                </div>
                <ArchitectureRules />
              </div>
              <AnimatePresence>
                {selectedTp && <TouchpointDetailPanel tpId={selectedTp} onClose={() => setSelectedTp(null)} />}
              </AnimatePresence>
            </div>
          </motion.div>
        )}
        {activeTab === "adrs" && (
          <motion.div key="adrs" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}>
            <div className="space-y-3">
              <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Architecture Decision Records — {ADR_REGISTRY.length} decisions</div>
              {ADR_REGISTRY.map(adr => (
                <div key={adr.id} className="bg-white border border-border rounded-xl p-5 space-y-2">
                  <div className="flex items-start justify-between gap-3 flex-wrap">
                    <div className="flex items-center gap-2">
                      <span className="text-xs font-bold text-[#003A8F] bg-[#003A8F]/10 px-2 py-0.5 rounded">{adr.id}</span>
                      <span className="font-semibold text-foreground text-sm">{adr.title}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium border ${
                        adr.status === "ACCEPTED" ? "bg-emerald-50 text-emerald-800 border-emerald-200" :
                        adr.status === "PROPOSED" ? "bg-amber-50 text-amber-800 border-amber-200" :
                        "bg-slate-100 text-slate-600 border-slate-200"
                      }`}>{adr.status}</span>
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium border ${
                        adr.impact === "High" ? "bg-red-50 text-red-800 border-red-200" :
                        adr.impact === "Medium" ? "bg-amber-50 text-amber-800 border-amber-200" :
                        "bg-slate-100 text-slate-600 border-slate-200"
                      }`}>{adr.impact} Impact</span>
                      <span className="text-xs text-muted-foreground">{adr.date}</span>
                    </div>
                  </div>
                  <p className="text-sm text-muted-foreground leading-relaxed">{adr.decision}</p>
                </div>
              ))}
            </div>
          </motion.div>
        )}
        {activeTab === "openitems" && (
          <motion.div key="openitems" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}>
            <div className="space-y-3">
              <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Open Architecture Items — {OPEN_ITEMS.length} items requiring resolution</div>
              {OPEN_ITEMS.map(item => (
                <div key={item.id} className="bg-white border border-border rounded-xl p-5 space-y-2">
                  <div className="flex items-start justify-between gap-3 flex-wrap">
                    <div className="flex items-center gap-2">
                      <span className="text-xs font-bold text-amber-700 bg-amber-50 border border-amber-200 px-2 py-0.5 rounded">{item.id}</span>
                      <span className="font-semibold text-foreground text-sm">{item.title}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium border ${
                        item.priority === "High" ? "bg-red-50 text-red-800 border-red-200" :
                        item.priority === "Medium" ? "bg-amber-50 text-amber-800 border-amber-200" :
                        "bg-slate-100 text-slate-600 border-slate-200"
                      }`}>{item.priority} Priority</span>
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium border ${
                        item.status === "OPEN" ? "bg-red-50 text-red-800 border-red-200" :
                        item.status === "IN_REVIEW" ? "bg-amber-50 text-amber-800 border-amber-200" :
                        "bg-emerald-50 text-emerald-800 border-emerald-200"
                      }`}>{item.status}</span>
                    </div>
                  </div>
                  <p className="text-sm text-muted-foreground leading-relaxed">{item.description}</p>
                  <div className="text-xs text-muted-foreground">Owner: <span className="font-medium text-foreground">{item.owner}</span></div>
                </div>
              ))}
            </div>
          </motion.div>
        )}
        {activeTab === "dependencies" && (
          <motion.div key="dependencies" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}>
            <div className="space-y-3">
              <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Platform Dependencies — {DEPENDENCIES.length} tracked</div>
              {DEPENDENCIES.map(dep => (
                <div key={dep.id} className={`bg-white border rounded-xl p-5 space-y-2 ${
                  dep.blocking ? "border-red-200" : "border-border"
                }`}>
                  <div className="flex items-start justify-between gap-3 flex-wrap">
                    <div className="flex items-center gap-2">
                      <span className="text-xs font-bold text-blue-700 bg-blue-50 border border-blue-200 px-2 py-0.5 rounded">{dep.id}</span>
                      <span className="font-semibold text-foreground text-sm">{dep.name}</span>
                      {dep.blocking && (
                        <span className="text-xs bg-red-100 text-red-800 border border-red-200 px-2 py-0.5 rounded-full font-bold">BLOCKING</span>
                      )}
                    </div>
                    <span className={`text-xs px-2 py-0.5 rounded-full font-medium border ${
                      dep.status === "IN_PROGRESS" ? "bg-blue-50 text-blue-800 border-blue-200" :
                      dep.status === "PLANNED" ? "bg-slate-100 text-slate-600 border-slate-200" :
                      dep.status === "COMPLETE" ? "bg-emerald-50 text-emerald-800 border-emerald-200" :
                      "bg-red-50 text-red-800 border-red-200"
                    }`}>{dep.status}</span>
                  </div>
                  <p className="text-sm text-muted-foreground leading-relaxed">{dep.description}</p>
                  <div className="text-xs text-muted-foreground">Owner: <span className="font-medium text-foreground">{dep.owner}</span></div>
                </div>
              ))}

              {/* Entry Points & Ingestion Contract */}
              <div className="bg-[#003A8F]/5 border border-[#003A8F]/20 rounded-xl p-5 space-y-3">
                <div className="text-xs font-bold uppercase tracking-wider text-[#003A8F]">Ingestion Contract — Enforced by Tax Portal</div>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <div className="text-xs font-semibold text-muted-foreground mb-1">Required Fields</div>
                    <div className="flex gap-2 flex-wrap">
                      {INGESTION_CONTRACT.requiredFields.map(f => (
                        <span key={f} className="text-xs bg-[#003A8F] text-white px-2 py-0.5 rounded font-mono">{f}</span>
                      ))}
                    </div>
                  </div>
                  <div>
                    <div className="text-xs font-semibold text-muted-foreground mb-1">Rejection Rule</div>
                    <div className="text-xs text-foreground">{INGESTION_CONTRACT.rejectionRule}</div>
                  </div>
                </div>
                <div>
                  <div className="text-xs font-semibold text-muted-foreground mb-2">Entry Points → Tax Portal</div>
                  <div className="flex gap-2 flex-wrap">
                    {ENTRY_POINTS.map(ep => (
                      <div key={ep.name} className="bg-white border border-[#003A8F]/20 rounded-lg px-3 py-1.5">
                        <div className="text-xs font-semibold text-[#003A8F]">{ep.name}</div>
                        <div className="text-xs text-muted-foreground">{ep.description}</div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {/* System Ownership */}
              <div className="bg-white border border-border rounded-xl p-5">
                <div className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-3">System Ownership Model</div>
                <div className="space-y-2">
                  {SYSTEM_OWNERSHIP.map(sys => (
                    <div key={sys.system} className="flex items-center gap-3 py-2 border-b border-border last:border-0">
                      <div className="w-3 h-3 rounded-full shrink-0" style={{ backgroundColor: sys.colorHex }} />
                      <div className="w-28 font-semibold text-sm text-foreground shrink-0">{sys.system}</div>
                      <div className="text-xs text-muted-foreground flex-1">{sys.role}</div>
                      <div className="text-xs text-muted-foreground shrink-0">{sys.owner}</div>
                      {sys.sor && (
                        <span className="text-xs bg-emerald-100 text-emerald-800 border border-emerald-200 px-2 py-0.5 rounded-full font-bold shrink-0">SOR</span>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <footer className="pt-4 pb-2 border-t border-border">
        <div className="flex items-center justify-between text-xs text-muted-foreground">
          <span>DCT Platform Architecture View · RSM | CATT · v3.1</span>
          <span>Visio diagram: Architecture Sync Agent · Interactive: platformData.ts</span>
        </div>
      </footer>
    </div>
  );
}
