// Architecture View — Platform Architecture Layers v3.1
// RSM | CATT | DCT Platform Executive Demo Environment
// Two-tab view: Visio Diagram (generated by Architecture Sync Agent) + Interactive Swimlane

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Shield, Database, Brain, ArrowDown, CheckCircle2,
  FileText, Link2, Play, GitBranch, ShieldCheck, ArrowRight, X,
  Image, Layers, Download, RefreshCw
} from "lucide-react";
import {
  PLATFORM_LAYERS, TOUCHPOINTS, AGENTS, getAgent, getLayer,
  type PlatformLayer, type EnrichedTouchpoint
} from "@/lib/platformData";

// ─── AGENT ICONS ─────────────────────────────────────────────────────────────

const AGENT_ICONS: Record<string, React.ElementType> = {
  analyst: FileText, architecture: GitBranch, qa: ShieldCheck,
  demo_runner: Play, roger_ai: Brain,
};

// ─── TOUCHPOINT CHIP ─────────────────────────────────────────────────────────

const TP_STATUS_DOT: Record<string, string> = {
  COMPLETE: "bg-emerald-400", IN_PROGRESS: "bg-blue-400",
  PENDING: "bg-amber-400", PLANNED: "bg-slate-300", BLOCKED: "bg-red-400",
};

function TouchpointChip({ tp, onClick, selected }: {
  tp: EnrichedTouchpoint;
  onClick: () => void;
  selected: boolean;
}) {
  const agent = tp.agentId ? getAgent(tp.agentId) : null;
  return (
    <button
      onClick={onClick}
      className={`flex items-center gap-2 px-3 py-2 rounded-lg border transition-all text-left ${
        selected
          ? "bg-white shadow-md border-white/60 scale-105"
          : "bg-white/10 border-white/20 hover:bg-white/20"
      }`}
    >
      <div className={`w-2 h-2 rounded-full shrink-0 ${TP_STATUS_DOT[tp.status]}`} />
      <div>
        <div className={`text-xs font-bold ${selected ? "text-foreground" : "text-white"}`}>{tp.id}</div>
        <div className={`text-xs leading-tight max-w-[7rem] ${selected ? "text-muted-foreground" : "text-white/70"}`}>
          {tp.name.split(" ").slice(0, 3).join(" ")}
        </div>
        {agent && (
          <div className={`text-xs mt-0.5 ${selected ? "text-[#003A8F]" : "text-white/60"}`}>
            {agent.name.split(" ")[0]}
          </div>
        )}
      </div>
    </button>
  );
}

// ─── LAYER ROW ────────────────────────────────────────────────────────────────

function LayerRow({ layer, touchpoints, selectedTp, onSelectTp }: {
  layer: PlatformLayer;
  touchpoints: EnrichedTouchpoint[];
  selectedTp: string | null;
  onSelectTp: (id: string | null) => void;
}) {
  const layerAgents = AGENTS.filter(a => a.layerId === layer.id);

  return (
    <div className="rounded-xl overflow-hidden border border-white/10">
      {/* Header */}
      <div className={`${layer.color} px-5 py-3`}>
        <div className="flex items-center justify-between flex-wrap gap-2">
          <div className="flex items-center gap-3">
            <div>
              <div className="flex items-center gap-2 flex-wrap">
                <span className="text-sm font-bold text-white">{layer.label}</span>
                {layer.isSystemOfRecord && (
                  <span className="text-xs bg-white/20 text-white px-2 py-0.5 rounded-full font-semibold border border-white/30">
                    ◆ AUTHORITY
                  </span>
                )}
              </div>
              <div className="text-xs text-white/80 mt-0.5">{layer.sublabel}</div>
            </div>
          </div>
          <div className="flex items-center gap-2 flex-wrap">
            {layer.systems.map(s => (
              <span key={s} className="text-xs bg-white/15 text-white px-2 py-0.5 rounded border border-white/20">{s}</span>
            ))}
            <span className="text-xs bg-white/10 text-white/80 px-2 py-0.5 rounded-full border border-white/20">
              {layer.authority}
            </span>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="bg-slate-800/60 px-5 py-3">
        <div className="flex items-start gap-6 flex-wrap">
          {touchpoints.length > 0 ? (
            <div className="flex-1">
              <div className="text-xs font-semibold uppercase tracking-wider text-slate-400 mb-2">Touchpoints</div>
              <div className="flex flex-wrap gap-2">
                {touchpoints.map(tp => (
                  <TouchpointChip
                    key={tp.id} tp={tp}
                    selected={selectedTp === tp.id}
                    onClick={() => onSelectTp(selectedTp === tp.id ? null : tp.id)}
                  />
                ))}
              </div>
            </div>
          ) : (
            <div className="flex-1">
              <div className="text-xs text-slate-500 italic">Source systems — no platform touchpoints</div>
            </div>
          )}

          {layerAgents.length > 0 && (
            <div className="shrink-0">
              <div className="text-xs font-semibold uppercase tracking-wider text-slate-400 mb-2">Agents</div>
              <div className="flex flex-col gap-1.5">
                {layerAgents.map(agent => {
                  const Icon = AGENT_ICONS[agent.id] || Brain;
                  return (
                    <div key={agent.id} className="flex items-center gap-2 bg-white/10 rounded-lg px-3 py-1.5 border border-white/10">
                      <div className={`w-5 h-5 rounded ${agent.color} flex items-center justify-center`}>
                        <Icon className="w-3 h-3 text-white" />
                      </div>
                      <div>
                        <div className="text-xs font-medium text-white">{agent.name}</div>
                        <div className="text-xs text-slate-400">{agent.status}</div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// ─── TOUCHPOINT DETAIL PANEL ─────────────────────────────────────────────────

function TouchpointDetailPanel({ tpId, onClose }: { tpId: string; onClose: () => void }) {
  const tp = TOUCHPOINTS.find(t => t.id === tpId);
  if (!tp) return null;
  const agent = tp.agentId ? getAgent(tp.agentId) : null;
  const layer = getLayer(tp.layerId);

  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: 20 }}
      className="bg-white border border-border rounded-xl shadow-lg p-5 w-80 shrink-0 self-start sticky top-0"
    >
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <div className={`w-8 h-8 rounded-full ${layer?.color || "bg-slate-500"} flex items-center justify-center text-white text-xs font-bold`}>
            {tp.id}
          </div>
          <div>
            <div className="text-sm font-bold text-foreground">{tp.id}</div>
            <div className="text-xs text-muted-foreground">{tp.name}</div>
          </div>
        </div>
        <button onClick={onClose} className="text-muted-foreground hover:text-foreground">
          <X className="w-4 h-4" />
        </button>
      </div>

      <div className="space-y-3 text-xs">
        <Row label="System Owner" value={tp.system} />
        <Row label="Platform Layer" value={layer?.label || ""} sub={layer?.authority} />
        <Row label="Executing Agent" value={agent?.name || "Practitioner / Manual"} sub={agent?.role} />
        <Row label="Gate" value={tp.gate} />
        <Row label="Authority Action" value={tp.isAuthorityAction ? "Yes — establishes platform authority" : "No"} />

        <div>
          <div className="font-semibold uppercase tracking-wider text-muted-foreground mb-1">Responsibility</div>
          <p className="text-muted-foreground leading-relaxed">{tp.responsibility}</p>
        </div>

        <div>
          <div className="font-semibold uppercase tracking-wider text-muted-foreground mb-1">Inputs</div>
          <div className="space-y-0.5">
            {tp.inputs.map((inp, i) => (
              <div key={i} className="text-muted-foreground flex items-start gap-1">
                <ArrowRight className="w-3 h-3 text-[#003A8F] shrink-0 mt-0.5" />{inp}
              </div>
            ))}
          </div>
        </div>

        <div>
          <div className="font-semibold uppercase tracking-wider text-muted-foreground mb-1">Outputs</div>
          <div className="space-y-0.5">
            {tp.outputs.map((out, i) => (
              <div key={i} className="text-muted-foreground flex items-start gap-1">
                <CheckCircle2 className="w-3 h-3 text-emerald-500 shrink-0 mt-0.5" />{out}
              </div>
            ))}
          </div>
        </div>
      </div>
    </motion.div>
  );
}

function Row({ label, value, sub }: { label: string; value: string; sub?: string }) {
  return (
    <div>
      <div className="font-semibold uppercase tracking-wider text-muted-foreground">{label}</div>
      <div className="font-medium text-foreground mt-0.5">{value}</div>
      {sub && <div className="text-muted-foreground">{sub}</div>}
    </div>
  );
}

// ─── ARCHITECTURE RULES ───────────────────────────────────────────────────────

function ArchitectureRules() {
  return (
    <div className="bg-[#003A8F] rounded-xl p-5 text-white">
      <div className="text-xs font-bold uppercase tracking-widest text-blue-200 mb-3">Architecture Rules — Enforced</div>
      <div className="grid grid-cols-2 gap-3">
        {[
          { icon: Brain, rule: "AI Orchestrator (Roger AI) = Stateless Compute", sub: "Performs T2, T3, T8 — never system of record" },
          { icon: Database, rule: "PDC = Canonical Financial Authority", sub: "All financial data authority flows through PDC" },
          { icon: Shield, rule: "TDC = Tax Decision Authority", sub: "All tax decisions persisted immutably in TDC" },
          { icon: CheckCircle2, rule: "Roger UI = Read-Only Consumer", sub: "Surfaces data only — no write operations" },
        ].map((r, i) => (
          <div key={i} className="flex items-start gap-2">
            <r.icon className="w-4 h-4 text-blue-300 shrink-0 mt-0.5" />
            <div>
              <div className="text-xs font-semibold text-white">{r.rule}</div>
              <div className="text-xs text-blue-200/80">{r.sub}</div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ─── VISIO DIAGRAM TAB ────────────────────────────────────────────────────────

const VISIO_CDN_URL = "https://d2xsxph8kpxj0f.cloudfront.net/310519663402976610/6z8sjWGC7ihkVcDSZGqeBn/DCT_Platform_Architecture_e863f691.png";

function VisioDiagramTab() {
  const [zoomed, setZoomed] = useState(false);

  return (
    <div className="space-y-4">
      {/* Metadata bar */}
      <div className="flex items-center justify-between bg-[#003A8F]/5 border border-[#003A8F]/20 rounded-xl px-4 py-3">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-[#003A8F] flex items-center justify-center">
            <RefreshCw className="w-4 h-4 text-white" />
          </div>
          <div>
            <div className="text-xs font-bold text-foreground">Architecture Sync Agent — Generated Diagram</div>
            <div className="text-xs text-muted-foreground">DCT_Platform_Architecture.pptx · v1.0.0 · Generated Mar 11, 2026</div>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <span className="flex items-center gap-1.5 text-xs bg-emerald-100 text-emerald-800 border border-emerald-200 px-2.5 py-1 rounded-full font-medium">
            <div className="w-1.5 h-1.5 rounded-full bg-emerald-500" />Synced
          </span>
          <a
            href={VISIO_CDN_URL}
            download="DCT_Platform_Architecture.png"
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-1.5 text-xs bg-white border border-border text-muted-foreground px-2.5 py-1 rounded-full font-medium hover:border-[#003A8F]/40 hover:text-[#003A8F] transition-colors"
          >
            <Download className="w-3 h-3" />Download PNG
          </a>
        </div>
      </div>

      {/* Architecture rules strip */}
      <div className="grid grid-cols-4 gap-2">
        {[
          { label: "AI Orchestrator", rule: "Stateless Compute", color: "bg-blue-50 border-blue-200 text-blue-800" },
          { label: "PDC", rule: "Financial Authority", color: "bg-emerald-50 border-emerald-200 text-emerald-800" },
          { label: "TDC", rule: "Tax Decision Authority", color: "bg-red-50 border-red-200 text-red-800" },
          { label: "Roger UI", rule: "Read-Only Consumer", color: "bg-pink-50 border-pink-200 text-pink-800" },
        ].map(r => (
          <div key={r.label} className={`border rounded-lg px-3 py-2 ${r.color}`}>
            <div className="text-xs font-bold">{r.label}</div>
            <div className="text-xs opacity-80">{r.rule}</div>
          </div>
        ))}
      </div>

      {/* Diagram */}
      <div
        className="bg-white border border-border rounded-xl overflow-hidden shadow-sm cursor-zoom-in"
        onClick={() => setZoomed(true)}
      >
        <div className="bg-[#003A8F] px-4 py-2 flex items-center justify-between">
          <span className="text-xs font-semibold text-white">DCT Platform Architecture — Swimlane View · T1–T11 Runtime Flow</span>
          <span className="text-xs text-blue-200">Click to enlarge</span>
        </div>
        <img
          src={VISIO_CDN_URL}
          alt="DCT Platform Architecture Diagram"
          className="w-full h-auto object-contain"
        />
        <div className="bg-slate-50 border-t border-border px-4 py-2 flex items-center justify-between">
          <span className="text-xs text-muted-foreground">Generated by Architecture Sync Agent · Source: arch_model.py · 7 swimlanes · 11 touchpoints</span>
          <span className="text-xs text-muted-foreground">DCT_Platform_Architecture.pptx · 31 KB</span>
        </div>
      </div>

      {/* Swimlane legend */}
      <div className="bg-white border border-border rounded-xl p-4">
        <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-3">Swimlane Legend</div>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
          {[
            { lane: "Client Source Systems", tps: "—", color: "bg-slate-100 border-slate-300" },
            { lane: "DMS / Phoenix", tps: "T1", color: "bg-violet-100 border-violet-300" },
            { lane: "AI Orchestrator", tps: "T2, T3, T8", color: "bg-blue-100 border-blue-300" },
            { lane: "PDC Data Foundation", tps: "T4, T5, T6, T7", color: "bg-emerald-100 border-emerald-300" },
            { lane: "AI Mapping Layer", tps: "T8", color: "bg-cyan-100 border-cyan-300" },
            { lane: "TDC Tax Decision Core", tps: "T9, T10", color: "bg-red-100 border-red-300" },
            { lane: "Roger UI", tps: "T11", color: "bg-pink-100 border-pink-300" },
          ].map(l => (
            <div key={l.lane} className={`border rounded-lg px-3 py-2 ${l.color}`}>
              <div className="text-xs font-medium text-foreground">{l.lane}</div>
              <div className="text-xs text-muted-foreground mt-0.5">{l.tps}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Lightbox */}
      <AnimatePresence>
        {zoomed && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/80 z-50 flex items-center justify-center p-6 cursor-zoom-out"
            onClick={() => setZoomed(false)}
          >
            <motion.div
              initial={{ scale: 0.9 }}
              animate={{ scale: 1 }}
              exit={{ scale: 0.9 }}
              className="bg-white rounded-xl overflow-hidden shadow-2xl max-w-6xl w-full"
              onClick={e => e.stopPropagation()}
            >
              <div className="bg-[#003A8F] px-4 py-2 flex items-center justify-between">
                <span className="text-xs font-semibold text-white">DCT Platform Architecture — Full View</span>
                <button onClick={() => setZoomed(false)} className="text-white/70 hover:text-white">
                  <X className="w-4 h-4" />
                </button>
              </div>
              <img src={VISIO_CDN_URL} alt="DCT Platform Architecture" className="w-full h-auto" />
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// ─── MAIN PAGE ────────────────────────────────────────────────────────────────

export default function ArchitectureView() {
  const [selectedTp, setSelectedTp] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<"visio" | "interactive">("visio");

  const tpsByLayer = (layerId: string) =>
    TOUCHPOINTS.filter(tp => tp.layerId === layerId);

  return (
    <div className="p-6 space-y-5">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-lg font-bold text-foreground">Platform Architecture</h1>
          <p className="text-xs text-muted-foreground mt-0.5">
            6 layers · 11 touchpoints · 5 AI agents · T1–T11 runtime flow
          </p>
        </div>
      </div>

      {/* Tab switcher */}
      <div className="flex gap-1 bg-slate-100 rounded-xl p-1 w-fit">
        <button
          onClick={() => setActiveTab("visio")}
          className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-semibold transition-all ${
            activeTab === "visio"
              ? "bg-white text-[#003A8F] shadow-sm border border-border"
              : "text-muted-foreground hover:text-foreground"
          }`}
        >
          <Image className="w-3.5 h-3.5" />
          Visio Diagram
          <span className="text-xs bg-[#003A8F]/10 text-[#003A8F] px-1.5 py-0.5 rounded font-medium">Sync Agent</span>
        </button>
        <button
          onClick={() => { setActiveTab("interactive"); setSelectedTp(null); }}
          className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-semibold transition-all ${
            activeTab === "interactive"
              ? "bg-white text-[#003A8F] shadow-sm border border-border"
              : "text-muted-foreground hover:text-foreground"
          }`}
        >
          <Layers className="w-3.5 h-3.5" />
          Interactive Swimlane
          <span className="text-xs bg-slate-200 text-slate-600 px-1.5 py-0.5 rounded font-medium">Clickable</span>
        </button>
      </div>

      {/* Tab content */}
      <AnimatePresence mode="wait">
        {activeTab === "visio" ? (
          <motion.div
            key="visio"
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
          >
            <VisioDiagramTab />
          </motion.div>
        ) : (
          <motion.div
            key="interactive"
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
          >
            <div className="flex gap-5 items-start">
              <div className="flex-1 space-y-2">
                <div className="bg-slate-900 rounded-2xl p-4 space-y-2">
                  <div className="text-xs font-semibold uppercase tracking-widest text-slate-400 mb-3 px-1">
                    DCT Platform Architecture Stack — T1–T11 Runtime Flow · Click any touchpoint for detail
                  </div>
                  {PLATFORM_LAYERS.map((layer, i) => (
                    <div key={layer.id}>
                      <LayerRow
                        layer={layer}
                        touchpoints={tpsByLayer(layer.id)}
                        selectedTp={selectedTp}
                        onSelectTp={setSelectedTp}
                      />
                      {i < PLATFORM_LAYERS.length - 1 && (
                        <div className="flex justify-center py-1">
                          <ArrowDown className="w-4 h-4 text-slate-500" />
                        </div>
                      )}
                    </div>
                  ))}
                </div>
                <ArchitectureRules />
              </div>

              <AnimatePresence>
                {selectedTp && (
                  <TouchpointDetailPanel
                    tpId={selectedTp}
                    onClose={() => setSelectedTp(null)}
                  />
                )}
              </AnimatePresence>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <footer className="pt-4 pb-2 border-t border-border">
        <div className="flex items-center justify-between text-xs text-muted-foreground">
          <span>DCT Platform Architecture View · RSM | CATT · v3.1</span>
          <span>Visio diagram: Architecture Sync Agent · Interactive: platformData.ts</span>
        </div>
      </footer>
    </div>
  );
}
