// Architecture View — Platform Architecture Layers v3.1
// RSM | CATT | DCT Platform Executive Demo Environment
// Two-tab view: Visio Diagram (generated by Architecture Sync Agent) + Interactive Swimlane

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Shield, Database, Brain, ArrowDown, CheckCircle2,
  FileText, Link2, Play, GitBranch, ShieldCheck, ArrowRight, X,
  Image, Layers, Download, Maximize2, Move, Zap
} from "lucide-react";
import SimulationPanel from "@/components/SimulationPanel";
import {
  PLATFORM_LAYERS, TOUCHPOINTS, AGENTS, getAgent, getLayer,
  ADR_REGISTRY, OPEN_ITEMS, DEPENDENCIES, ARCHITECTURE_GUARDRAILS,
  SYSTEM_OWNERSHIP, ENTRY_POINTS, INGESTION_CONTRACT, ARCH_METADATA,
  type PlatformLayer, type EnrichedTouchpoint
} from "@/lib/platformData";

// ─── AGENT ICONS ─────────────────────────────────────────────────────────────

const AGENT_ICONS: Record<string, React.ElementType> = {
  analyst: FileText, architecture: GitBranch, qa: ShieldCheck,
  demo_runner: Play, roger_ai: Brain,
};

// ─── TOUCHPOINT CHIP ─────────────────────────────────────────────────────────

const TP_STATUS_DOT: Record<string, string> = {
  COMPLETE: "bg-emerald-400", IN_PROGRESS: "bg-blue-400",
  PENDING: "bg-amber-400", PLANNED: "bg-slate-300", BLOCKED: "bg-red-400",
};

function TouchpointChip({ tp, onClick, selected }: {
  tp: EnrichedTouchpoint;
  onClick: () => void;
  selected: boolean;
}) {
  const agent = tp.agentId ? getAgent(tp.agentId) : null;
  return (
    <button
      onClick={onClick}
      className={`flex items-center gap-2 px-3 py-2 rounded-lg border transition-all text-left ${
        selected
          ? "bg-white shadow-md border-white/60 scale-105"
          : "bg-white/10 border-white/20 hover:bg-white/20"
      }`}
    >
      <div className={`w-2 h-2 rounded-full shrink-0 ${TP_STATUS_DOT[tp.status]}`} />
      <div>
        <div className={`text-xs font-bold ${selected ? "text-foreground" : "text-white"}`}>{tp.id}</div>
        <div className={`text-xs leading-tight max-w-[7rem] ${selected ? "text-muted-foreground" : "text-white/70"}`}>
          {tp.name.split(" ").slice(0, 3).join(" ")}
        </div>
        {agent && (
          <div className={`text-xs mt-0.5 ${selected ? "text-[#003A8F]" : "text-white/60"}`}>
            {agent.name.split(" ")[0]}
          </div>
        )}
      </div>
    </button>
  );
}

// ─── LAYER ROW ────────────────────────────────────────────────────────────────

function LayerRow({ layer, touchpoints, selectedTp, onSelectTp }: {
  layer: PlatformLayer;
  touchpoints: EnrichedTouchpoint[];
  selectedTp: string | null;
  onSelectTp: (id: string | null) => void;
}) {
  const layerAgents = AGENTS.filter(a => a.layerId === layer.id);

  return (
    <div className="rounded-xl overflow-hidden border border-white/10">
      {/* Header */}
      <div className={`${layer.color} px-5 py-3`}>
        <div className="flex items-center justify-between flex-wrap gap-2">
          <div className="flex items-center gap-3">
            <div>
              <div className="flex items-center gap-2 flex-wrap">
                <span className="text-sm font-bold text-white">{layer.label}</span>
                {layer.isSystemOfRecord && (
                  <span className="text-xs bg-white/20 text-white px-2 py-0.5 rounded-full font-semibold border border-white/30">
                    ◆ AUTHORITY
                  </span>
                )}
              </div>
              <div className="text-xs text-white/80 mt-0.5">{layer.sublabel}</div>
            </div>
          </div>
          <div className="flex items-center gap-2 flex-wrap">
            {layer.systems.map(s => (
              <span key={s} className="text-xs bg-white/15 text-white px-2 py-0.5 rounded border border-white/20">{s}</span>
            ))}
            <span className="text-xs bg-white/10 text-white/80 px-2 py-0.5 rounded-full border border-white/20">
              {layer.authority}
            </span>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="bg-slate-800/60 px-5 py-3">
        <div className="flex items-start gap-6 flex-wrap">
          {touchpoints.length > 0 ? (
            <div className="flex-1">
              <div className="text-xs font-semibold uppercase tracking-wider text-slate-400 mb-2">Touchpoints</div>
              <div className="flex flex-wrap gap-2">
                {touchpoints.map(tp => (
                  <TouchpointChip
                    key={tp.id} tp={tp}
                    selected={selectedTp === tp.id}
                    onClick={() => onSelectTp(selectedTp === tp.id ? null : tp.id)}
                  />
                ))}
              </div>
            </div>
          ) : (
            <div className="flex-1">
              <div className="text-xs text-slate-500 italic">Source systems — no platform touchpoints</div>
            </div>
          )}

          {layerAgents.length > 0 && (
            <div className="shrink-0">
              <div className="text-xs font-semibold uppercase tracking-wider text-slate-400 mb-2">Agents</div>
              <div className="flex flex-col gap-1.5">
                {layerAgents.map(agent => {
                  const Icon = AGENT_ICONS[agent.id] || Brain;
                  return (
                    <div key={agent.id} className="flex items-center gap-2 bg-white/10 rounded-lg px-3 py-1.5 border border-white/10">
                      <div className={`w-5 h-5 rounded ${agent.color} flex items-center justify-center`}>
                        <Icon className="w-3 h-3 text-white" />
                      </div>
                      <div>
                        <div className="text-xs font-medium text-white">{agent.name}</div>
                        <div className="text-xs text-slate-400">{agent.status}</div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// ─── TOUCHPOINT DETAIL PANEL ─────────────────────────────────────────────────

function TouchpointDetailPanel({ tpId, onClose }: { tpId: string; onClose: () => void }) {
  const tp = TOUCHPOINTS.find(t => t.id === tpId);
  if (!tp) return null;
  const agent = tp.agentId ? getAgent(tp.agentId) : null;
  const layer = getLayer(tp.layerId);

  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: 20 }}
      className="bg-white border border-border rounded-xl shadow-lg p-5 w-80 shrink-0 self-start sticky top-0"
    >
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <div className={`w-8 h-8 rounded-full ${layer?.color || "bg-slate-500"} flex items-center justify-center text-white text-xs font-bold`}>
            {tp.id}
          </div>
          <div>
            <div className="text-sm font-bold text-foreground">{tp.id}</div>
            <div className="text-xs text-muted-foreground">{tp.name}</div>
          </div>
        </div>
        <button onClick={onClose} className="text-muted-foreground hover:text-foreground">
          <X className="w-4 h-4" />
        </button>
      </div>

      <div className="space-y-3 text-xs">
        <Row label="System Owner" value={tp.system} />
        <Row label="Platform Layer" value={layer?.label || ""} sub={layer?.authority} />
        <Row label="Executing Agent" value={agent?.name || "Practitioner / Manual"} sub={agent?.role} />
        <Row label="Gate" value={tp.gate} />
        <Row label="Authority Action" value={tp.isAuthorityAction ? "Yes — establishes platform authority" : "No"} />

        <div>
          <div className="font-semibold uppercase tracking-wider text-muted-foreground mb-1">Responsibility</div>
          <p className="text-muted-foreground leading-relaxed">{tp.responsibility}</p>
        </div>

        <div>
          <div className="font-semibold uppercase tracking-wider text-muted-foreground mb-1">Inputs</div>
          <div className="space-y-0.5">
            {tp.inputs.map((inp, i) => (
              <div key={i} className="text-muted-foreground flex items-start gap-1">
                <ArrowRight className="w-3 h-3 text-[#003A8F] shrink-0 mt-0.5" />{inp}
              </div>
            ))}
          </div>
        </div>

        <div>
          <div className="font-semibold uppercase tracking-wider text-muted-foreground mb-1">Outputs</div>
          <div className="space-y-0.5">
            {tp.outputs.map((out, i) => (
              <div key={i} className="text-muted-foreground flex items-start gap-1">
                <CheckCircle2 className="w-3 h-3 text-emerald-500 shrink-0 mt-0.5" />{out}
              </div>
            ))}
          </div>
        </div>
      </div>
    </motion.div>
  );
}

function Row({ label, value, sub }: { label: string; value: string; sub?: string }) {
  return (
    <div>
      <div className="font-semibold uppercase tracking-wider text-muted-foreground">{label}</div>
      <div className="font-medium text-foreground mt-0.5">{value}</div>
      {sub && <div className="text-muted-foreground">{sub}</div>}
    </div>
  );
}

// ─── ARCHITECTURE RULES ───────────────────────────────────────────────────────

function ArchitectureRules() {
  return (
    <div className="bg-[#003A8F] rounded-xl p-5 text-white">
      <div className="text-xs font-bold uppercase tracking-widest text-blue-200 mb-3">Architecture Rules — Enforced</div>
      <div className="grid grid-cols-2 gap-3">
        {[
          { icon: Brain, rule: "AI Orchestrator (Roger AI) = Stateless Compute", sub: "Performs T2, T3, T8 — never system of record" },
          { icon: Database, rule: "PDC = Canonical Financial Authority", sub: "All financial data authority flows through PDC" },
          { icon: Shield, rule: "TDC = Tax Decision Authority", sub: "All tax decisions persisted immutably in TDC" },
          { icon: CheckCircle2, rule: "Roger UI = Read-Only Consumer", sub: "Surfaces data only — no write operations" },
        ].map((r, i) => (
          <div key={i} className="flex items-start gap-2">
            <r.icon className="w-4 h-4 text-blue-300 shrink-0 mt-0.5" />
            <div>
              <div className="text-xs font-semibold text-white">{r.rule}</div>
              <div className="text-xs text-blue-200/80">{r.sub}</div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ─── VISIO DIAGRAM TAB ────────────────────────────────────────────────────────

const PLATFORM_ARCH_CDN_URL = "https://d2xsxph8kpxj0f.cloudfront.net/310519663402976610/6z8sjWGC7ihkVcDSZGqeBn/DCT_Platform_Architecture_v1_3176731c.png";

// ─── ZOOM PAN VIEWER (used only for Full Platform Architecture tab) ───────────

function ZoomPanViewer({ src, alt }: { src: string; alt: string }) {
  const BASE_WIDTH = 2600;
  const STEP = 400;
  const MIN_W = 1200;
  const MAX_W = 6000;
  const [imageWidth, setImageWidth] = useState(BASE_WIDTH);
  const [fullscreen, setFullscreen] = useState(false);
  const clampW = (w: number) => Math.min(MAX_W, Math.max(MIN_W, w));
  const zoomIn  = () => setImageWidth(w => clampW(w + STEP));
  const zoomOut = () => setImageWidth(w => clampW(w - STEP));
  const reset   = () => setImageWidth(BASE_WIDTH);
  const pct = Math.round((imageWidth / BASE_WIDTH) * 100);

  return (
    <>
      <div className="bg-white border border-border rounded-xl overflow-hidden shadow-sm">
        <div className="bg-[#003A8F] px-4 py-2.5 flex items-center justify-between gap-2">
          <span className="text-xs font-semibold text-white truncate">DCT Platform — Full Stack Architecture</span>
          <div className="flex items-center gap-2 shrink-0">
            <span className="text-xs text-blue-200 font-mono tabular-nums w-12 text-right">{pct}%</span>
            <button onClick={zoomOut} title="Zoom out" className="w-7 h-7 rounded flex items-center justify-center hover:bg-white/20 text-white transition-colors text-base font-bold">−</button>
            <button onClick={reset} title="Reset" className="px-2.5 py-1 rounded text-xs font-bold hover:bg-white/20 text-white border border-white/40 transition-colors">Reset</button>
            <button onClick={zoomIn} title="Zoom in" className="w-7 h-7 rounded flex items-center justify-center hover:bg-white/20 text-white transition-colors text-base font-bold">+</button>
            <div className="w-px h-4 bg-white/30 mx-1" />
            <button onClick={() => setFullscreen(true)} title="Full screen" className="w-7 h-7 rounded flex items-center justify-center hover:bg-white/20 text-white transition-colors"><Maximize2 className="w-3.5 h-3.5" /></button>
            <a href={src} download="DCT_Platform_Architecture.png" target="_blank" rel="noopener noreferrer" title="Download PNG" className="w-7 h-7 rounded flex items-center justify-center hover:bg-white/20 text-white transition-colors"><Download className="w-3.5 h-3.5" /></a>
          </div>
        </div>
        <div className="bg-slate-50 border-b border-border px-4 py-1.5 flex items-center gap-2">
          <Move className="w-3 h-3 text-muted-foreground shrink-0" />
          <span className="text-xs text-muted-foreground">Scroll to navigate · Use + / − to resize · Reset returns to default width · Full screen for presentations</span>
        </div>
        <div className="overflow-auto bg-[#f0f2f5]" style={{ height: "700px" }}>
          <img src={src} alt={alt} draggable={false} style={{ width: imageWidth, height: "auto", display: "block", userSelect: "none" }} />
        </div>
        <div className="bg-slate-50 border-t border-border px-4 py-2 flex items-center justify-between">
          <span className="text-xs text-muted-foreground">Source: {ARCH_METADATA.sourceOfTruth} · {ARCH_METADATA.layerCount} swimlanes · {ARCH_METADATA.touchpointCount} touchpoints</span>
          <button onClick={() => setFullscreen(true)} className="text-xs text-[#003A8F] font-semibold hover:underline flex items-center gap-1">
            <Maximize2 className="w-3 h-3" /> Open full screen
          </button>
        </div>
      </div>
      <AnimatePresence>
        {fullscreen && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 bg-[#0a1628] flex flex-col">
            <div className="bg-[#003A8F] px-4 py-2.5 flex items-center justify-between gap-2">
              <span className="text-xs font-semibold text-white truncate">DCT Platform — Full Stack Architecture</span>
              <div className="flex items-center gap-2 shrink-0">
                <span className="text-xs text-blue-200 font-mono tabular-nums w-12 text-right">{pct}%</span>
                <button onClick={zoomOut} className="w-7 h-7 rounded flex items-center justify-center hover:bg-white/20 text-white transition-colors text-base font-bold">−</button>
                <button onClick={reset} className="px-2.5 py-1 rounded text-xs font-bold hover:bg-white/20 text-white border border-white/40 transition-colors">Reset</button>
                <button onClick={zoomIn} className="w-7 h-7 rounded flex items-center justify-center hover:bg-white/20 text-white transition-colors text-base font-bold">+</button>
                <div className="w-px h-4 bg-white/30 mx-1" />
                <button onClick={() => setFullscreen(false)} className="w-7 h-7 rounded flex items-center justify-center hover:bg-white/20 text-white transition-colors"><X className="w-3.5 h-3.5" /></button>
              </div>
            </div>
            <div className="flex-1 overflow-auto bg-[#f0f2f5]">
              <img src={src} alt={alt} draggable={false} style={{ width: imageWidth, height: "auto", display: "block", userSelect: "none" }} />
            </div>
            <div className="bg-[#0F2A5C] px-4 py-2 text-xs text-blue-300 text-center">
              RSM | CATT · DCT Platform Full Stack Architecture · Click × to close
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}

// ─── VISIO SWIMLANE PROCESS FLOW — EXACT MATCH TO REFERENCE SITE ─────────────
// Source: rsm-ai-team-niua6bzx.manus.space/#visio-arch
// Colors: gray=platform/entry, green=PDC, purple=AI Orchestrator, gray=Roger, yellow=TDC

// ── Shared sub-components ────────────────────────────────────────────────────

function TpBadge({ id }: { id: string }) {
  return (
    <span className="inline-flex items-center justify-center w-7 h-7 rounded-full bg-[#1e3a5f] text-white text-xs font-bold shrink-0">
      {id}
    </span>
  );
}

function FlowArrow({ label, dashed = false }: { label: string; dashed?: boolean }) {
  return (
    <div className="flex flex-col items-center py-2">
      <div className={`w-px h-5 ${dashed ? "border-l-2 border-dashed border-slate-400" : "bg-slate-400"}`} />
      <div className="w-2 h-2 border-r-2 border-b-2 border-slate-400 rotate-45 -mt-1.5" />
      {label && <div className="text-xs text-slate-500 mt-1 text-center">{label}</div>}
    </div>
  );
}

function SectionHeader({
  num, title, owner, color, tpId,
}: { num: number; title: string; owner: string; color: string; tpId?: string }) {
  return (
    <div className={`${color} px-5 py-3 flex items-center gap-3`}>
      <div className="w-7 h-7 rounded-full bg-white/25 flex items-center justify-center text-sm font-bold text-white shrink-0">
        {num}
      </div>
      <div className="flex-1">
        <div className="text-sm font-bold text-white uppercase tracking-wide">{title}</div>
        <div className="text-xs text-white/80 mt-0.5">Owner: {owner}</div>
      </div>
      {tpId && <TpBadge id={tpId} />}
    </div>
  );
}

function AnnotationBox({ text }: { text: string }) {
  return (
    <div className="bg-blue-50 border border-blue-200 rounded px-3 py-2">
      <span className="text-xs font-bold text-blue-800">Annotation: </span>
      <span className="text-xs text-blue-700">{text}</span>
    </div>
  );
}

function WarningBox({ text }: { text: string }) {
  return (
    <div className="bg-red-50 border border-red-200 rounded px-3 py-2 flex items-start gap-2">
      <span className="text-red-500 shrink-0 text-sm">⚠</span>
      <span className="text-xs text-red-700">{text}</span>
    </div>
  );
}

function ContentBox({ title, owner, items, className = "" }: {
  title: string; owner?: string; items: string[]; className?: string;
}) {
  return (
    <div className={`bg-white border border-slate-200 rounded p-3 ${className}`}>
      {title && <div className="text-xs font-bold text-slate-800 mb-1">{title}</div>}
      {owner && <div className="text-xs text-blue-700 font-semibold mb-1">{owner}</div>}
      <ul className="space-y-0.5">
        {items.map((item, i) => (
          <li key={i} className="text-xs text-slate-600 flex items-start gap-1.5">
            <span className="text-slate-400 shrink-0 mt-0.5">•</span>
            <span>{item}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

// ── TOUCHPOINT LEGEND DATA ────────────────────────────────────────────────────

const TP_LEGEND_DATA = [
  { id: "T1", name: "File Ingestion via Tax Portal", step: "Step 1", batch: "Batch 1", system: "Tax Portal", desc: "Tax Portal generates DocumentId (GUID) + JobId (GUID), validates EntityId + PeriodStart + PeriodEnd, publishes NEW_FILE_EVENT to file_ingestion_events." },
  { id: "T2", name: "PDC Record Creation", step: "Step 2", batch: "Batch 1", system: "PDC", desc: "PDC persists IngestionJob (GUID ids, PeriodStart/PeriodEnd) + SourceFile. Status enum = INGESTED. Service Bus is transport only — no processing or enrichment." },
  { id: "T3", name: "AI Processing Trigger", step: "Step 3", batch: "Batch 2", system: "PDC → AI Orchestrator", desc: "PDC advances record state to PROCESSING and invokes the AI Orchestrator once per file." },
  { id: "T4", name: "AI Agent Pipeline Execution", step: "Step 4", batch: "Batch 2 / 2A", system: "AI Orchestrator", desc: "Agent chain: File Recognizer → File Normalizer → Cross-LOB Mapper → Tax Mapper. Stateless agents persist via APIs. Batch 2A gap: Orchestrator must return FirmTaxonomyId (from Taxonomy Service) with every record. ClassificationStatus = CLASSIFIED | UNCLASSIFIED | OVERRIDE." },
  { id: "T5", name: "Canonical Dataset Persistence", step: "Step 4", batch: "Batch 2 / 2A", system: "PDC", desc: "PDC persists normalized FinancialFact records + Cross-LOB mappings. Assigns RunId (GUID) + SourceRecordId (GUID). Status enum = READY. FirmTaxonomyId is a REQUIRED field on every FinancialFact record (enforcement active after Batch 2A). READY signal blocked if any record has ClassificationStatus = UNCLASSIFIED." },
  { id: "T6", name: "Tax Record Creation in TDC", step: "Step 4", batch: "Batch 3", system: "TDC", desc: "Tax mapping proposals stored in TDC. TDC assigns tdc_record_id and preserves full lineage." },
  { id: "T7", name: "Roger Primary Read Contract", step: "Step 5", batch: "Batch 4", system: "Roger Web App", desc: "Roger retrieves tax mapping proposals and decisions via TDC read contract. Read-only consumer of TDC. This is the moment the platform comes to life for a practitioner." },
  { id: "T8", name: "Practitioner Review & Adjustment", step: "Step 6", batch: "Batch 6", system: "Roger Web App", desc: "Review tasks generated automatically from data state. Practitioner creates, submits, approves, and locks book-to-tax adjustments. Sign-off is non-repudiable. Lock is terminal." },
  { id: "T9", name: "Tax-Ready Record Derivation", step: "Step 7", batch: "Batch 6", system: "TDC", desc: "Tax-ready records derived deterministically from accepted mapping decisions and approved book-to-tax adjustments only. UNRESOLVED records persisted where practitioner decision is missing." },
  { id: "T10", name: "TDC Finalization — TAX_READY / Lock", step: "Step 8", batch: "Batch 6", system: "TDC", desc: "Finalization requires non-repudiable sign-off. Lock is terminal — mutation attempts rejected and logged. Unlock transitions entity to AMENDED through a governed operation." },
];

// ── MAIN COMPONENT ────────────────────────────────────────────────────────────

// ─── EXECUTIVE DEMO STEPS ────────────────────────────────────────────────────

const EXEC_DEMO_STEPS = [
  {
    step: 1, title: "Client File Arrives at Tax Portal",
    system: "Tax Portal · Platform",
    color: "bg-blue-700",
    highlight: "section-1",
    narrative: "A client uploads their Trial Balance from SAP. Tax Portal is the single ingestion gate — it validates EntityId, PeriodStart, PeriodEnd, assigns an immutable DocumentId (GUID) and JobId (GUID), and publishes a NEW_FILE_EVENT to the Service Bus. TaxYear is NOT in the payload.",
    keyFact: "DocumentId is the immutable lineage anchor for every downstream record.",
    fields: ["ClientId (GUID)", "EntityId (GUID)", "DocumentId (GUID) — immutable", "PeriodStart / PeriodEnd", "NEW_FILE_EVENT → Service Bus"],
  },
  {
    step: 2, title: "PDC Receives Event & Creates Initial Record",
    system: "PDC · DCT",
    color: "bg-emerald-700",
    highlight: "section-2",
    narrative: "PDC listens on the Service Bus and immediately persists an IngestionJob record before AI is ever invoked. Status is set to INGESTED. TaxYear is NOT stored in PDC — it is derived later in TDC from PeriodStart.",
    keyFact: "An audit record exists in PDC before any AI processing begins.",
    fields: ["IngestionJob persisted", "Status = INGESTED", "TaxYear NOT stored (derived in TDC)", "Retry-safe: PDC holds backlog"],
  },
  {
    step: 3, title: "PDC Triggers AI Orchestrator — Single Invocation",
    system: "PDC → AI Orchestrator",
    color: "bg-green-700",
    highlight: "section-3",
    narrative: "PDC advances the record to PROCESSING and invokes the AI Orchestrator exactly once per file. This is the only AI invocation for this file. The Orchestrator is stateless — it does not own data.",
    keyFact: "PDC has one integration point: the Orchestrator. TDC never invokes the Orchestrator.",
    fields: ["JobId (GUID)", "PeriodStart / PeriodEnd", "file metadata", "TaxYear NOT passed"],
  },
  {
    step: 4, title: "AI Orchestrator — Stage 1: File Recognition & Normalization",
    system: "AI Orchestrator · Roger Team",
    color: "bg-purple-700",
    highlight: "section-4",
    narrative: "Agent 1 (File Recognizer) pattern-matches the file against canonical schemas. Agent 2 (File Normalizer) extracts raw data and transforms it into the standard canonical format. Output: normalized canonical records ready for cross-LOB mapping.",
    keyFact: "Agents are stateless — all persistence flows through PDC or TDC APIs.",
    fields: ["Agent 1 — File Recognizer", "Agent 2 — File Normalizer", "Output: Normalized canonical records"],
  },
  {
    step: 5, title: "AI Orchestrator — Stage 2: Cross-LOB Taxonomy & FirmTaxonomyId",
    system: "AI Orchestrator → PDC · Batch 2A",
    color: "bg-amber-600",
    highlight: "section-4-batch2a",
    narrative: "Agent 3 (Cross-LOB / Firm Taxonomy Mapper) maps each normalized record to the firm's financial taxonomy using the Taxonomy Service. Each record receives a FirmTaxonomyId (GUID) and ClassificationStatus. The Orchestrator calls the PDC API to persist these records. ⚠ Batch 2A Gap: Orchestrator is NOT currently returning FirmTaxonomyId — this is the blocking gap Batch 2A resolves.",
    keyFact: "FirmTaxonomyId is REQUIRED on every PDC FinancialFact record. READY signal is blocked if any record is UNCLASSIFIED.",
    fields: ["FirmTaxonomyId (GUID) — from Taxonomy Service", "ClassificationStatus (CLASSIFIED | UNCLASSIFIED | OVERRIDE)", "RunId (GUID)", "SourceRecordId (GUID) per record", "⚠ Batch 2A: Orchestrator gap — not yet returning FirmTaxonomyId"],
  },
  {
    step: 6, title: "AI Orchestrator — Stage 3: Tax Taxonomy (TDC)",
    system: "AI Orchestrator → TDC",
    color: "bg-purple-700",
    highlight: "section-4",
    narrative: "Agent 4 (Tax Taxonomy Mapper) maps each cross-LOB mapped record to the tax taxonomy. It pulls tax taxonomy tables from TDC API (read-only) and produces proposed tax line, confidence band (GREEN / YELLOW / RED), and evidence. Results are written to TDC via API.",
    keyFact: "TdcRecordId (GUID) is assigned. Confidence band drives practitioner review priority.",
    fields: ["TdcRecordId (GUID)", "ConfidenceBand (GREEN | YELLOW | RED)", "Tax mapping proposals", "Evidence / reasoning"],
  },
  {
    step: 7, title: "Roger Web App — Practitioner Review",
    system: "Roger Web App · Roger Team",
    color: "bg-slate-600",
    highlight: "section-5",
    narrative: "Roger retrieves tax mapping proposals from TDC via the primary read contract. This is the moment the platform comes to life for a practitioner. Roger is read-only — it never runs AI, mutates PDC, or mutates TDC directly.",
    keyFact: "All API calls are scoped by ClientId + EntityId + PeriodStart + PeriodEnd. No TaxYear parameter.",
    fields: ["GET /api/tdc/records?entityId=...&periodStart=...&periodEnd=...", "GET /api/tdc/records/{id}/lineage", "Read-only consumer"],
  },
  {
    step: 8, title: "Practitioner Approves, Corrects, or Overrides",
    system: "Practitioner via Roger UI",
    color: "bg-slate-500",
    highlight: "section-6",
    narrative: "The practitioner reviews AI proposals and takes action: approve, correct, or override. Cross-LOB meaning changes route to PDC (new FinancialFact version). Tax classification changes route to TDC (new MappingDecision appended). All operations are append-only.",
    keyFact: "Locked records are immutable. Sign-off is non-repudiable.",
    fields: ["Approve / Correct / Override", "Cross-LOB change → PDC (new GUID version)", "Tax change → TDC (appended)", "Lifecycle: Draft → Submitted → Approved → Locked"],
  },
  {
    step: 9, title: "TDC Finalization — TAX_READY",
    system: "TDC · DCT",
    color: "bg-yellow-600",
    highlight: "section-8",
    narrative: "After practitioner sign-off, TDC finalizes the record as TAX_READY. The lock is terminal — mutation attempts are rejected and logged. Tax truth is finalized here. TDC versions all decisions.",
    keyFact: "TAX_READY is the authoritative signal that a record is ready for filing and downstream consumption.",
    fields: ["Status: TAX_READY", "Lock is terminal", "TDC versions all decisions", "Audit trail complete"],
  },
  {
    step: 10, title: "Downstream Consumption — PDC READY & TDC TAX_READY",
    system: "Any Domain Subscriber",
    color: "bg-cyan-700",
    highlight: "section-downstream",
    narrative: "Any domain can subscribe to PDC READY and TDC TAX_READY signals without requiring changes to PDC or TDC. Roger reads from TDC only. IMS receives outbound outputs only. The full lineage chain — DocumentId → FirmTaxonomyId → SourceRecordId → TdcRecordId — is traceable end-to-end.",
    keyFact: "Platform extensibility: new domains subscribe to existing signals. No PDC/TDC changes required.",
    fields: ["PDC READY → Tax · Audit · Consulting · any LOB", "TDC TAX_READY → Filing · Reporting", "Lineage: DocumentId → FirmTaxonomyId → SourceRecordId → TdcRecordId"],
  },
];

function VisioDiagramTab() {
  const [selectedTp, setSelectedTp] = useState<string | null>(null);
  const [demoOpen, setDemoOpen] = useState(false);
  const [simOpen, setSimOpen] = useState(false);
  const [demoStep, setDemoStep] = useState(0);

  const currentStep = EXEC_DEMO_STEPS[demoStep];
  const isFirst = demoStep === 0;
  const isLast = demoStep === EXEC_DEMO_STEPS.length - 1;

  // Keyboard navigation for demo
  useEffect(() => {
    if (!demoOpen) return;
    const handler = (e: KeyboardEvent) => {
      if (e.key === "ArrowRight" || e.key === " ") { e.preventDefault(); if (!isLast) setDemoStep(s => s + 1); }
      if (e.key === "ArrowLeft") { e.preventDefault(); if (!isFirst) setDemoStep(s => s - 1); }
      if (e.key === "Escape") setDemoOpen(false);
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [demoOpen, isFirst, isLast]);

  return (
    <div className="space-y-0">

      {/* ── EXECUTIVE DEMO MODAL ─────────────────────────────────────────────── */}
      <AnimatePresence>
        {demoOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4"
            onClick={(e) => { if (e.target === e.currentTarget) setDemoOpen(false); }}
          >
            <motion.div
              initial={{ scale: 0.95, y: 20 }}
              animate={{ scale: 1, y: 0 }}
              exit={{ scale: 0.95, y: 20 }}
              className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl overflow-hidden"
            >
              {/* Header */}
              <div className={`${currentStep.color} px-6 py-4 flex items-center justify-between`}>
                <div>
                  <div className="text-xs font-bold uppercase tracking-widest text-white/70 mb-0.5">
                    RSM DCT · Executive Demo · Step {currentStep.step} of {EXEC_DEMO_STEPS.length}
                  </div>
                  <div className="text-lg font-bold text-white">{currentStep.title}</div>
                  <div className="text-xs text-white/80 mt-0.5">{currentStep.system}</div>
                </div>
                <button onClick={() => setDemoOpen(false)} className="w-8 h-8 rounded-full bg-white/20 hover:bg-white/30 flex items-center justify-center text-white transition-colors">
                  <X className="w-4 h-4" />
                </button>
              </div>

              {/* Progress bar */}
              <div className="h-1.5 bg-slate-200">
                <div
                  className={`h-full ${currentStep.color} transition-all duration-500`}
                  style={{ width: `${((demoStep + 1) / EXEC_DEMO_STEPS.length) * 100}%` }}
                />
              </div>

              {/* Step dots */}
              <div className="flex items-center justify-center gap-1.5 pt-3 px-6">
                {EXEC_DEMO_STEPS.map((s, i) => (
                  <button
                    key={s.step}
                    onClick={() => setDemoStep(i)}
                    className={`rounded-full transition-all ${
                      i === demoStep ? "w-4 h-4 bg-[#003A8F]" :
                      i < demoStep ? "w-2.5 h-2.5 bg-slate-400" :
                      "w-2.5 h-2.5 bg-slate-200"
                    }`}
                    title={`Step ${s.step}: ${s.title}`}
                  />
                ))}
              </div>

              {/* Body */}
              <div className="px-6 py-4 space-y-4">
                {/* Narrative */}
                <p className="text-sm text-slate-700 leading-relaxed">{currentStep.narrative}</p>

                {/* Key Fact */}
                <div className="bg-[#003A8F]/8 border border-[#003A8F]/20 rounded-lg px-4 py-3">
                  <div className="text-xs font-bold uppercase tracking-wider text-[#003A8F] mb-1">Key Governance Fact</div>
                  <div className="text-sm font-semibold text-[#003A8F]">{currentStep.keyFact}</div>
                </div>

                {/* Fields */}
                <div>
                  <div className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">Data Fields / Outputs</div>
                  <div className="flex flex-wrap gap-1.5">
                    {currentStep.fields.map((f, i) => (
                      <span
                        key={i}
                        className={`text-xs px-2.5 py-1 rounded-full font-mono border ${
                          f.startsWith("⚠")
                            ? "bg-amber-50 text-amber-800 border-amber-300 font-semibold"
                            : f.includes("FirmTaxonomyId")
                            ? "bg-violet-50 text-violet-800 border-violet-300 font-semibold"
                            : f.includes("ClassificationStatus")
                            ? "bg-violet-50 text-violet-700 border-violet-200"
                            : "bg-slate-100 text-slate-700 border-slate-200"
                        }`}
                      >
                        {f}
                      </span>
                    ))}
                  </div>
                </div>
              </div>

              {/* Footer nav */}
              <div className="px-6 py-4 bg-slate-50 border-t border-slate-200 flex items-center justify-between">
                <button
                  onClick={() => isFirst ? setDemoOpen(false) : setDemoStep(s => s - 1)}
                  className="text-xs font-semibold text-slate-600 hover:text-slate-900 px-4 py-2 rounded-lg border border-slate-300 bg-white hover:bg-slate-50 transition-colors"
                >
                  {isFirst ? "Close" : "← Back"}
                </button>
                <div className="text-xs text-slate-400">← → Arrow keys · Space to advance · Esc to close</div>
                {isLast ? (
                  <button
                    onClick={() => setDemoOpen(false)}
                    className="text-xs font-semibold bg-emerald-700 text-white px-4 py-2 rounded-lg hover:bg-emerald-800 transition-colors flex items-center gap-1.5"
                  >
                    <CheckCircle2 className="w-3.5 h-3.5" /> Demo Complete
                  </button>
                ) : (
                  <button
                    onClick={() => setDemoStep(s => s + 1)}
                    className="text-xs font-semibold bg-[#003A8F] text-white px-4 py-2 rounded-lg hover:bg-[#002a6e] transition-colors flex items-center gap-1.5"
                  >
                    Next — {EXEC_DEMO_STEPS[demoStep + 1].title.split(" ").slice(0, 4).join(" ")}… <ArrowRight className="w-3.5 h-3.5" />
                  </button>
                )}
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* ── Page Header ─────────────────────────────────────────────────────── */}
      <div className="bg-white border border-border rounded-xl px-5 py-4 mb-4">
        <div className="text-xs font-bold uppercase tracking-widest text-slate-400 mb-1">
          RSM CATT · DCT PLATFORM · ARCHITECTURE REVIEW DOCUMENT
        </div>
        <h2 className="text-xl font-bold text-slate-900">
          DCT Platform Architecture — End-to-End Flow for Roger Platform
        </h2>
        <div className="text-xs text-slate-500 mt-1">
          Baseline v1.0 &nbsp;|&nbsp; Owner: DCT &nbsp;|&nbsp; Agentic Execution Model
        </div>
        <div className="mt-3 flex flex-wrap gap-2">
          <button
            onClick={() => { setDemoStep(0); setDemoOpen(true); }}
            className="inline-flex items-center gap-1.5 text-xs bg-[#003A8F] text-white px-3 py-1.5 rounded font-semibold hover:bg-[#002a6e] transition-colors"
          >
            <Play className="w-3 h-3" /> Executive Demo
          </button>
          <button
            onClick={() => setSimOpen(true)}
            className="inline-flex items-center gap-1.5 text-xs bg-[#059669] text-white px-3 py-1.5 rounded font-semibold hover:bg-[#047857] transition-colors"
          >
            <Zap className="w-3 h-3" /> Run End-to-End Simulation
          </button>
          <button className="inline-flex items-center gap-1.5 text-xs bg-white border border-slate-300 text-slate-600 px-3 py-1.5 rounded font-medium">
            <Download className="w-3 h-3" /> Export SVG <span className="text-slate-400 ml-1">[Ctrl+Shift+E]</span>
          </button>
          <button className="inline-flex items-center gap-1.5 text-xs bg-white border border-slate-300 text-slate-600 px-3 py-1.5 rounded font-medium">
            <Download className="w-3 h-3" /> Export PNG
          </button>
          <button className="inline-flex items-center gap-1.5 text-xs bg-white border border-slate-300 text-slate-600 px-3 py-1.5 rounded font-medium">
            <FileText className="w-3 h-3" /> Copy to Clipboard <span className="text-slate-400 ml-1">[Ctrl+Shift+C]</span>
          </button>
        </div>
        <div className="mt-3 space-y-0.5 text-center">
          {[
            "1. Tax Portal is the single ingestion gate.",
            "2. AI Orchestrator runs once.",
            "3. PDC owns cross-LOB truth.",
            "4. TDC owns tax truth.",
            "5. Roger reads and surfaces practitioner decisions.",
          ].map((g, i) => (
            <div key={i} className="text-xs text-slate-500">{g}</div>
          ))}
        </div>
      </div>

      {/* ── SECTION 1: Platform Entry & Ingestion ───────────────────────────── */}
      <div className="border border-slate-300 rounded-xl overflow-hidden mb-3">
        <SectionHeader num={1} title="Platform Entry & Ingestion" owner="Platform" color="bg-slate-600" />
        <div className="bg-slate-50 px-5 py-3">
          <div className="text-xs text-slate-500 mb-3">
            All entry points converge into Tax Portal, which enforces the ingestion contract and publishes the event to the Service Bus
          </div>
          {/* Entry points */}
          <div className="flex flex-wrap items-center gap-2 mb-2">
            {["Direct Upload", "Roger Web App", "Phoenix (future)", "Duo / DSDMS (transition)"].map(ep => (
              <span key={ep} className="text-xs border border-slate-300 bg-white rounded px-3 py-1.5 text-slate-700">{ep}</span>
            ))}
            <span className="text-xs text-slate-400">→ converge →</span>
            <span className="text-xs bg-blue-600 text-white rounded px-3 py-1.5 font-semibold">Tax Portal</span>
          </div>
          <div className="text-xs text-slate-400 mb-2">All entry points → Tax Portal</div>
        </div>

        {/* Tax Portal block */}
        <div className="bg-blue-600 px-5 py-3">
          <div className="flex items-center gap-2 mb-3">
            <span className="text-sm font-bold text-white uppercase tracking-wide">TAX PORTAL</span>
            <span className="text-xs text-blue-200">Owner: Platform · Single ingestion gate</span>
            <TpBadge id="T1" />
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            <ContentBox
              title="Ingestion Gate"
              owner="Owner: Platform"
              items={[
                "Generate DocumentId (GUID) — immutable",
                "Generate JobId (GUID)",
                "Validate ClientId (GUID) — REQUIRED",
                "Validate EntityId (GUID) — REQUIRED",
                "Validate PeriodStart + PeriodEnd — REQUIRED",
                "Enforce: PeriodEnd >= PeriodStart",
                "Document registration",
                "Publish NEW_FILE_EVENT",
              ]}
            />
            <ContentBox
              title="NEW_FILE_EVENT Contract"
              items={[
                "ClientId: GUID — REQUIRED",
                "EntityId: GUID — REQUIRED",
                "DocumentId: GUID (immutable)",
                "JobId: GUID",
                "PeriodStart: DateOnly — REQUIRED",
                "PeriodEnd: DateOnly — REQUIRED",
                "DocumentType: enum",
                "Timestamp: datetime",
                "SourceSystem: string",
                "RequestedBy: string",
                "Note: TaxYear NOT in payload",
              ]}
            />
            <AnnotationBox text="Tax Portal enforces ingestion contract across all entry points." />
          </div>
        </div>

        <FlowArrow label="NEW_FILE_EVENT → Service Bus" />

        {/* Service Bus block */}
        <div className="bg-slate-500 px-5 py-3">
          <div className="flex items-center gap-2 mb-3">
            <span className="text-sm font-bold text-white uppercase tracking-wide">SERVICE BUS</span>
            <span className="text-xs text-slate-200">Owner: Platform · Event handoff only</span>
            <TpBadge id="T2" />
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            <ContentBox
              title="Service Bus"
              owner="Owner: Platform"
              items={[
                "Topic: file_ingestion_events",
                "Consumer: PDC Ingestion Listener",
                "Payload: NEW_FILE_EVENT (no mutation)",
                "Delivery: at-least-once",
                "Replay supported",
              ]}
            />
            <AnnotationBox text="Service Bus is transport only — no processing or enrichment." />
            <WarningBox text="No other systems use the Service Bus. Tax Portal → PDC event handoff only." />
          </div>
        </div>

        <FlowArrow label="NEW_FILE_EVENT → PDC Listener" />
      </div>

      {/* ── SECTION 2: PDC Receives Event ───────────────────────────────────── */}
      <div className="border border-green-300 rounded-xl overflow-hidden mb-3">
        <SectionHeader num={2} title="PDC Receives Event & Persists Initial Record" owner="DCT" color="bg-green-700" />
        <div className="bg-green-50 px-5 py-4 space-y-3">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            {/* PDC Ingestion Listener */}
            <div className="bg-white border border-green-200 rounded p-3 md:col-span-2">
              <div className="text-xs font-bold text-slate-800 mb-2">PDC INGESTION LISTENER</div>
              <div className="text-xs text-slate-600 mb-1">PDC listens on the Service Bus for new file events.</div>
              <div className="text-xs text-slate-600 mb-1">Upon receipt PDC immediately persists:</div>
              <ul className="space-y-0.5 mb-2">
                {["ClientId (GUID) — REQUIRED","EntityId (GUID) — REQUIRED","DocumentId (GUID)","JobId (GUID)","PeriodStart (DateOnly) — REQUIRED","PeriodEnd (DateOnly) — REQUIRED","file metadata"].map((item,i) => (
                  <li key={i} className="text-xs text-slate-600 flex items-start gap-1.5"><span className="text-slate-400 shrink-0">•</span>{item}</li>
                ))}
              </ul>
              <div className="text-xs text-slate-500 italic mb-2">TaxYear is NOT stored in PDC — it is derived in TDC from PeriodStart.</div>
              <div className="text-xs text-slate-600">PDC sets initial record state: <span className="bg-green-600 text-white text-xs font-bold px-2 py-0.5 rounded">INGESTED</span></div>
              <div className="text-xs text-slate-500 italic mt-2">PDC owns all ingestion. Tax Portal is fully out of the picture. TaxYear NOT stored in PDC — derived in TDC from PeriodStart. No tax logic in PDC.</div>
            </div>
            {/* Right column */}
            <div className="space-y-2">
              <div className="bg-white border border-green-200 rounded p-3">
                <div className="text-xs font-bold text-slate-700 mb-1">Auditability from moment of arrival</div>
                <div className="text-xs text-slate-500">A record exists in PDC before AI is ever invoked.</div>
              </div>
              <div className="bg-white border border-green-200 rounded p-3">
                <div className="text-xs font-bold text-slate-700 mb-1">Retry safety</div>
                <div className="text-xs text-slate-500">If AI fails, PDC holds the backlog and can replay events.</div>
              </div>
              <div className="bg-white border border-green-200 rounded p-3">
                <div className="text-xs font-bold text-slate-700 mb-1">State machine begins</div>
                <div className="flex items-center gap-1 mt-1">
                  <span className="text-xs bg-green-600 text-white font-bold px-2 py-0.5 rounded">INGESTED</span>
                  <span className="text-slate-400 text-xs">→</span>
                  <span className="text-xs bg-blue-600 text-white font-bold px-2 py-0.5 rounded">PROCESSING</span>
                  <span className="text-slate-400 text-xs">→</span>
                  <span className="text-xs bg-green-600 text-white font-bold px-2 py-0.5 rounded">READY</span>
                </div>
              </div>
            </div>
          </div>

          {/* PDC schema section */}
          <div className="bg-white border border-green-200 rounded p-3">
            <div className="text-xs font-bold text-green-800 mb-2 uppercase tracking-wide">
              PDC — Phoenix Data Consolidation · Cross-LOB System of Record · Ingestion Persistence
            </div>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
              <div className="bg-white border border-slate-200 rounded p-3">
                <div className="text-xs font-bold text-slate-800 mb-1">IngestionJob</div>
                <div className="text-xs text-blue-700 font-semibold mb-1">Owner: DCT</div>
                <ul className="space-y-0.5">
                  {["JobId (GUID) — PRIMARY tracking key","ClientId (GUID) — REQUIRED","EntityId (GUID) — REQUIRED","PeriodStart (DateOnly) — REQUIRED","PeriodEnd (DateOnly) — REQUIRED","Status enum = INGESTED","CreatedTimestamp · RequestedBy · SourceSystem","Rule: TaxYear NOT stored — derived in TDC only"].map((item,i) => (
                    <li key={i} className="text-xs text-slate-600 flex items-start gap-1.5"><span className="text-slate-400 shrink-0 mt-0.5">•</span>{item}</li>
                  ))}
                </ul>
                <div className="mt-2 pt-2 border-t border-violet-200">
                  <div className="text-xs font-bold text-violet-800 mb-1">Batch 2A Fields (FinancialFact)</div>
                  <div className="flex flex-wrap gap-1">
                    <span className="text-xs bg-violet-100 text-violet-800 border border-violet-300 px-1.5 py-0.5 rounded font-bold">FirmTaxonomyId (GUID)</span>
                    <span className="text-xs bg-violet-50 text-violet-700 border border-violet-200 px-1.5 py-0.5 rounded">ClassificationStatus</span>
                  </div>
                  <div className="text-xs text-slate-500 mt-1">REQUIRED on every FinancialFact record after Batch 2A</div>
                </div>
              </div>
              <ContentBox
                title="SourceFile"
                items={[
                  "SourceFileId (GUID) — record key",
                  "DocumentId (GUID) — immutable lineage anchor",
                  "JobId FK (GUID) — links to IngestionJob",
                  "FileName · FileType · UploadTimestamp",
                  "DocumentType (enum)",
                ]}
              />
              <div className="bg-white border border-slate-200 rounded p-3">
                <div className="text-xs font-bold text-slate-800 mb-2">STATE MACHINE</div>
                <div className="flex flex-col gap-1">
                  <span className="text-xs bg-green-600 text-white font-bold px-2 py-1 rounded text-center">INGESTED</span>
                  <span className="text-slate-400 text-xs text-center">↓</span>
                  <span className="text-xs bg-blue-600 text-white font-bold px-2 py-1 rounded text-center">PROCESSING</span>
                  <span className="text-slate-400 text-xs text-center">↓</span>
                  <span className="text-xs bg-green-600 text-white font-bold px-2 py-1 rounded text-center">READY</span>
                </div>
              </div>
              <div className="bg-white border border-slate-200 rounded p-3">
                <div className="text-xs font-bold text-slate-800 mb-2">API</div>
                <div className="text-xs font-mono text-blue-700 break-all mb-2">GET /api/pdc/ingestion/status?jobId={"{JobId}"}</div>
                <div className="text-xs text-slate-600 font-semibold mb-1">Returns:</div>
                <ul className="space-y-0.5">
                  {["JobId (GUID) — primary key","DocumentId (GUID) — immutable","SourceFileId (GUID)","ClientId (GUID)","EntityId (GUID)","PeriodStart (DateOnly)","PeriodEnd (DateOnly)","State (INGESTED | PROCESSING | READY)"].map((item,i) => (
                    <li key={i} className="text-xs text-slate-500 flex items-start gap-1"><span className="shrink-0">•</span>{item}</li>
                  ))}
                  <li className="flex items-start gap-1 mt-1">
                    <span className="shrink-0">•</span>
                    <span className="text-xs font-bold text-violet-800 bg-violet-100 border border-violet-300 px-1 py-0.5 rounded">FirmTaxonomyId</span>
                    <span className="text-xs text-slate-500 ml-1">(Batch 2A)</span>
                  </li>
                </ul>
                <div className="mt-2 text-xs text-blue-700 italic">Annotation: Audit record exists before AI is invoked.</div>
              </div>
            </div>
          </div>
        </div>
        <FlowArrow label="PDC advances state to PROCESSING · prepares invocation payload" />
      </div>

      {/* ── SECTION 3: PDC → AI Orchestrator ────────────────────────────────── */}
      <div className="border border-green-300 rounded-xl overflow-hidden mb-3">
        <SectionHeader num={3} title="PDC → AI Orchestrator (Single Invocation)" owner="DCT (trigger) · Roger Team (execution)" color="bg-green-700" tpId="T3" />
        <div className="bg-green-50 px-5 py-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            <div className="bg-white border border-green-200 rounded p-3 md:col-span-1">
              <div className="text-xs font-bold text-slate-800 mb-2">ORCHESTRATOR INVOCATION</div>
              <div className="text-xs text-slate-600 mb-1">PDC advances the record state to:</div>
              <span className="text-xs bg-blue-600 text-white font-bold px-2 py-0.5 rounded">PROCESSING</span>
              <div className="text-xs text-slate-600 mt-2 mb-1">PDC then invokes the AI Orchestrator.</div>
              <div className="text-xs font-semibold text-slate-700 mb-1">This is the only AI invocation for this file.</div>
              <div className="text-xs text-slate-500 mt-2 mb-1 font-semibold">Invocation payload:</div>
              <ul className="space-y-0.5">
                {["JobId (GUID)","PeriodStart (DateOnly) — REQUIRED","PeriodEnd (DateOnly) — REQUIRED","file metadata","TaxYear is NOT passed — PeriodStart/PeriodEnd are the temporal model."].map((item,i) => (
                  <li key={i} className="text-xs text-slate-600 flex items-start gap-1.5"><span className="text-slate-400 shrink-0">•</span>{item}</li>
                ))}
              </ul>
              <div className="text-xs text-slate-500 italic mt-2">The AI Orchestrator is stateless — it does not persist data. All persistence occurs through PDC or TDC APIs. TDC does NOT invoke the Orchestrator.</div>
            </div>
            <WarningBox text="PDC and TDC never communicate directly. All coordination flows through the Orchestrator." />
            <ContentBox
              title="Single integration point"
              items={[
                "PDC has one integration point — the Orchestrator.",
                "PDC never invokes individual agents directly.",
                "There is no Service Bus between PDC and TDC.",
              ]}
            />
          </div>
        </div>
        <FlowArrow label="Single invocation per file · ClientId (GUID) + EntityId (GUID) + DocumentId (GUID) + PeriodStart + PeriodEnd + file_metadata" />
      </div>

      {/* ── SECTION 4: AI Orchestrator ──────────────────────────────────────── */}
      <div className="border border-purple-300 rounded-xl overflow-hidden mb-3">
        <SectionHeader num={4} title="AI Orchestrator" owner="Roger Team · Stateless compute layer" color="bg-purple-700" tpId="T4" />
        <div className="bg-purple-50 px-5 py-4 space-y-3">
          {/* Stage 1 + Stage 2 side by side */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {/* Stage 1 */}
            <div className="bg-purple-100 border border-purple-200 rounded p-3">
              <div className="text-xs font-bold text-purple-900 mb-2">STAGE 1 — File Recognition & Normalization (File Level)</div>
              <div className="text-xs text-purple-700 font-semibold mb-1 flex items-center gap-1">PDC API <ArrowRight className="w-3 h-3" /></div>
              <div className="mb-2">
                <div className="text-xs font-semibold text-slate-700 mb-1">Agent 1 — File Recognizer</div>
                <ul className="space-y-0.5">
                  {["Pattern-matches incoming file structure against canonical schemas","Pulls canonical schemas from PDC API (read-only)","Identifies document type (e.g., Trial Balance, K-1, W-2, 1099)"].map((item,i) => (
                    <li key={i} className="text-xs text-slate-600 flex items-start gap-1.5"><span className="text-slate-400 shrink-0">•</span>{item}</li>
                  ))}
                </ul>
              </div>
              <div className="mb-2">
                <div className="text-xs font-semibold text-slate-700 mb-1">Agent 2 — File Normalizer</div>
                <ul className="space-y-0.5">
                  {["Extracts raw data and transforms it into the standard canonical format for the identified document type","Pulls canonical schemas from PDC API (read-only)"].map((item,i) => (
                    <li key={i} className="text-xs text-slate-600 flex items-start gap-1.5"><span className="text-slate-400 shrink-0">•</span>{item}</li>
                  ))}
                </ul>
              </div>
              <div className="text-xs text-green-700 font-semibold">Output: Normalized canonical records</div>
            </div>
            {/* Stage 2 */}
            <div className="bg-green-50 border border-green-200 rounded p-3">
              <div className="text-xs font-bold text-green-900 mb-2">STAGE 2 — Cross-LOB Taxonomy (PDC) (Record Level)</div>
              <div className="text-xs text-green-700 font-semibold mb-1 flex items-center gap-1">TDC API <ArrowRight className="w-3 h-3" /></div>
              <div className="mb-2">
                <div className="text-xs font-semibold text-slate-700 mb-1">Agent 3 — Cross-LOB / Firm Taxonomy Mapper</div>
                <ul className="space-y-0.5">
                  {["Maps each normalized account record independently to the firm's financial taxonomy","Categories: asset, liability, equity, income, expense","Pulls firm and cross-LOB taxonomy tables from PDC API (read-only)"].map((item,i) => (
                    <li key={i} className="text-xs text-slate-600 flex items-start gap-1.5"><span className="text-slate-400 shrink-0">•</span>{item}</li>
                  ))}
                </ul>
              </div>
                <div className="bg-green-100 border border-green-300 rounded p-2 mb-2">
                <div className="text-xs font-bold text-green-800 mb-1">ORCHESTRATOR CALLS PDC API TO PERSIST:</div>
                <ul className="space-y-0.5">
                  {["Normalized canonical records","Cross-LOB taxonomy mappings at the record level","Records keyed by DocumentId (GUID), EntityId (GUID), PeriodStart, PeriodEnd"].map((item,i) => (
                    <li key={i} className="text-xs text-green-700 flex items-start gap-1.5"><span className="shrink-0">•</span>{item}</li>
                  ))}
                  <li className="flex items-start gap-1.5">
                    <span className="shrink-0">•</span>
                    <span className="text-xs font-bold text-violet-800 bg-violet-100 border border-violet-300 px-1.5 py-0.5 rounded">FirmTaxonomyId (GUID)</span>
                    <span className="text-xs text-green-700">— from Taxonomy Service · REQUIRED per Batch 2A</span>
                  </li>
                  <li className="flex items-start gap-1.5">
                    <span className="shrink-0">•</span>
                    <span className="text-xs font-bold text-violet-700 bg-violet-50 border border-violet-200 px-1.5 py-0.5 rounded">ClassificationStatus</span>
                    <span className="text-xs text-green-700">(CLASSIFIED | UNCLASSIFIED | OVERRIDE)</span>
                  </li>
                </ul>
              </div>
              <div className="bg-green-100 border border-green-300 rounded p-2 mb-2">
                <div className="text-xs font-bold text-green-800 mb-1">PDC RESPONDS WITH:</div>
                <ul className="space-y-0.5">
                  {["RunId (GUID) / versioned","SourceRecordId (GUID) for each persisted record","READY state confirmation"].map((item,i) => (
                    <li key={i} className="text-xs text-green-700 flex items-start gap-1.5"><span className="shrink-0">•</span>{item}</li>
                  ))}
                </ul>
              </div>
              <div className="flex items-center gap-2">
                <div className="text-xs text-green-700 font-semibold">Output: RunId (GUID) · SourceRecordId (GUID) · READY state</div>
                <TpBadge id="T5" />
              </div>
              <div className="text-xs text-slate-500 italic mt-1">PDC is the authoritative cross-LOB system of record. Stage 3 cannot begin until source_record_id is returned.</div>
            </div>
          </div>

          {/* Batch 2A Classification Gap Callout */}
          <div className="bg-amber-50 border-l-4 border-amber-500 rounded-r-lg px-4 py-3">
            <div className="flex items-start gap-3">
              <div className="shrink-0 mt-0.5">
                <span className="inline-flex items-center justify-center w-5 h-5 rounded-full bg-amber-500 text-white text-xs font-bold">!</span>
              </div>
              <div>
                <div className="text-xs font-bold text-amber-900 mb-1">Batch 2A Gap — Orchestrator Contract Enforcement &amp; Classification</div>
                <div className="text-xs text-amber-800 mb-2">
                  The AI Orchestrator is <span className="font-bold">NOT currently returning FirmTaxonomyId</span> with normalized records.
                  This is the blocking gap addressed by <span className="font-semibold">Batch 2A</span>.
                </div>
                <div className="flex flex-wrap gap-2">
                  <div className="bg-white border border-amber-200 rounded px-3 py-1.5">
                    <div className="text-xs font-bold text-slate-700">Current State</div>
                    <div className="text-xs text-red-700 font-semibold">FirmTaxonomyId = null (not returned)</div>
                    <div className="text-xs text-slate-500">ClassificationStatus = UNCLASSIFIED</div>
                  </div>
                  <span className="text-amber-400 text-lg self-center">→</span>
                  <div className="bg-white border border-green-200 rounded px-3 py-1.5">
                    <div className="text-xs font-bold text-slate-700">Expected State (post-Batch 2A)</div>
                    <div className="text-xs text-green-700 font-semibold">FirmTaxonomyId = GUID (REQUIRED)</div>
                    <div className="text-xs text-slate-500">ClassificationStatus = CLASSIFIED</div>
                  </div>
                  <div className="bg-white border border-slate-200 rounded px-3 py-1.5">
                    <div className="text-xs font-bold text-slate-700">Enforcement Rule</div>
                    <div className="text-xs text-slate-600">PDC rejects records missing FirmTaxonomyId</div>
                    <div className="text-xs text-slate-500">READY signal blocked if UNCLASSIFIED records exist</div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Stage 3 */}
          <div className="bg-purple-100 border border-purple-200 rounded p-3">
            <div className="text-xs font-bold text-purple-900 mb-2">STAGE 3 — Tax Taxonomy (TDC) (Record Level)</div>
            <div className="mb-2">
              <div className="text-xs font-semibold text-slate-700 mb-1">Agent 4 — Tax Taxonomy Mapper</div>
              <ul className="space-y-0.5">
                {["Maps each cross-LOB mapped account record independently to the tax taxonomy","Pulls tax taxonomy tables and rules from TDC API (read-only)","Produces proposed tax line, confidence band (GREEN / YELLOW / RED), and evidence / reasoning"].map((item,i) => (
                  <li key={i} className="text-xs text-slate-600 flex items-start gap-1.5"><span className="text-slate-400 shrink-0">•</span>{item}</li>
                ))}
              </ul>
            </div>
            <div className="flex items-center gap-2">
              <div className="text-xs text-purple-700 font-semibold">Output: TdcRecordId (GUID) · ConfidenceBand (enum: GREEN|YELLOW|RED) · tax mapping proposals</div>
              <TpBadge id="T6" />
            </div>
          </div>
          <WarningBox text="Agents never persist data directly. All results are written through PDC or TDC APIs." />
        </div>
        <FlowArrow label="Roger Query API (read-only) · GET /api/tdc/records" />
      </div>

      {/* ── SECTION 5: Roger Web Application ────────────────────────────────── */}
      <div className="border border-slate-300 rounded-xl overflow-hidden mb-3">
        <SectionHeader num={5} title="Roger Web Application" owner="Roger Team · UI layer only · Read-only consumer of TDC" color="bg-slate-600" tpId="T7" />
        <div className="bg-slate-50 px-5 py-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            <ContentBox
              title="Roger Web App"
              owner="Owner: Roger Team"
              items={["Tax mapping review","Confidence score display","Approve / Correct / Override","Lineage trace view"]}
            />
            <ContentBox
              title="API Calls"
              items={[
                "GET /api/tdc/records?entityId={guid}&periodStart={date}&periodEnd={date}",
                "GET /api/tdc/records/{tdcRecordId}/lineage",
                "Note: No TaxYear param — scoped by ClientId + EntityId + PeriodStart + PeriodEnd (REQUIRED)",
              ]}
            />
            <AnnotationBox text="Roger never: Runs AI · Mutates PDC · Mutates TDC · Bypasses APIs." />
          </div>
        </div>
        <FlowArrow label="Practitioner actions (dashed = user interaction)" dashed />
      </div>

      {/* ── SECTION 6: User Review & Adjustment ─────────────────────────────── */}
      <div className="border border-slate-300 rounded-xl overflow-hidden mb-3">
        <div className="bg-slate-500 px-5 py-3 flex items-center gap-3">
          <div className="w-7 h-7 rounded-full bg-white/25 flex items-center justify-center text-sm font-bold text-white shrink-0">6</div>
          <div className="flex-1">
            <div className="text-sm font-bold text-white">User Review & Adjustment (Human-in-the-loop)</div>
            <div className="text-xs text-white/80 mt-0.5">Owner: Practitioner (via Roger UI)</div>
          </div>
          <TpBadge id="T8" />
        </div>
        <div className="bg-slate-50 px-5 py-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            <ContentBox
              title="Practitioner Actions"
              items={["Approve tax mappings","Correct mapping errors","Reclassify accounts (e.g. liability → asset)","Override tax line assignments"]}
            />
            <ContentBox
              title="Adjustment Routing (Append-Only)"
              items={[
                "Cross-LOB meaning change → PDC (new FinancialFact version, GUID)",
                "Tax classification change → TDC (new MappingDecision appended)",
                "Both → PDC first, then TDC",
                "Lifecycle: Draft → Submitted → Approved → Applied → Locked",
                "No overwrites — append-only. Locked records are immutable.",
              ]}
            />
          </div>
        </div>
        <FlowArrow label="Adjustment routed to PDC and/or TDC via API" />
      </div>

      {/* ── SECTION 7: Adjustment Propagation ───────────────────────────────── */}
      <div className="border border-green-300 rounded-xl overflow-hidden mb-3">
        <SectionHeader num={7} title="Adjustment Propagation" owner="DCT · Corrections routed based on the nature of the change" color="bg-green-700" tpId="T9" />
        <div className="bg-green-50 px-5 py-4 space-y-3">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            <ContentBox
              title="Correction Types"
              items={["Cross-LOB meaning changed","Tax meaning only","Both (cross-LOB and tax)"]}
            />
            <ContentBox
              title="Routing Target"
              items={[
                "Cross-LOB meaning changed → PDC: new FinancialFact version (GUID)",
                "Tax meaning only → TDC: new MappingDecision appended (GUID)",
                "Both → PDC first (FinancialFact), then TDC (MappingDecision)",
                "LineageEvent appended with EventType=CORRECTION on each change",
              ]}
            />
          </div>
          <div className="bg-green-100 border border-green-200 rounded px-3 py-2 text-xs text-green-800">
            All downstream systems stay consistent regardless of the correction path.
          </div>
        </div>
        <FlowArrow label="Final state assignment → TDC" />
      </div>

      {/* ── SECTION 8: TDC Finalization ─────────────────────────────────────── */}
      <div className="border border-yellow-400 rounded-xl overflow-hidden mb-3">
        <SectionHeader num={8} title="TDC Finalization" owner="DCT · Authoritative tax record finalization and versioning" color="bg-yellow-600" tpId="T10" />
        <div className="bg-yellow-50 px-5 py-4 space-y-3">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            <div className="bg-white border border-yellow-200 rounded p-3">
              <div className="flex items-center gap-2 mb-2">
                <span className="text-xs bg-orange-100 border border-orange-300 text-orange-800 font-bold px-2 py-0.5 rounded">REVIEW_REQUIRED</span>
              </div>
              <div className="text-xs text-slate-600">After AI proposal — practitioner action required</div>
            </div>
            <div className="bg-white border border-yellow-200 rounded p-3">
              <div className="flex items-center gap-2 mb-2">
                <span className="text-xs bg-green-100 border border-green-300 text-green-800 font-bold px-2 py-0.5 rounded">TAX_READY</span>
              </div>
              <div className="text-xs text-slate-600">After practitioner approval and sign-off</div>
            </div>
          </div>
          <ul className="space-y-0.5">
            {["TDC versions all decisions","All final tax outcomes are stored as authoritative records"].map((item,i) => (
              <li key={i} className="text-xs text-slate-600 flex items-start gap-1.5"><span className="text-slate-400 shrink-0">•</span>{item}</li>
            ))}
          </ul>
          <div className="bg-yellow-500 rounded px-4 py-2 text-sm font-bold text-white text-center">
            Tax truth is finalized here.
          </div>
        </div>
        <FlowArrow label="PDC READY signal · TDC TAX_READY record" />
      </div>

      {/* ── Downstream Consumption ───────────────────────────────────────────── */}
      <div className="border border-cyan-300 rounded-xl overflow-hidden mb-3 bg-cyan-50">
        <div className="px-5 py-3 flex items-center gap-3 bg-cyan-100 border-b border-cyan-200">
          <span className="text-sm font-bold text-slate-800">Downstream Consumption</span>
          <span className="text-xs bg-cyan-600 text-white px-2 py-0.5 rounded font-semibold">PLATFORM EXTENSIBILITY</span>
        </div>
        <div className="px-5 py-4 space-y-3">
          <div className="text-xs text-slate-600">
            Any domain can subscribe to PDC and TDC outputs — no changes are required to PDC or TDC as new domains come online.
          </div>
          <table className="w-full text-xs border border-slate-200 rounded overflow-hidden">
            <thead>
              <tr className="bg-slate-100">
                <th className="text-left px-3 py-2 font-semibold text-slate-700">Signal</th>
                <th className="text-left px-3 py-2 font-semibold text-slate-700">Available To</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-t border-slate-200">
                <td className="px-3 py-2"><span className="text-xs bg-green-100 border border-green-300 text-green-800 font-bold px-2 py-0.5 rounded">PDC READY</span></td>
                <td className="px-3 py-2 text-slate-600">Tax · Audit · Consulting · any future LOB</td>
              </tr>
              <tr className="border-t border-slate-200">
                <td className="px-3 py-2"><span className="text-xs bg-yellow-100 border border-yellow-300 text-yellow-800 font-bold px-2 py-0.5 rounded">TDC TAX_READY</span></td>
                <td className="px-3 py-2 text-slate-600">Tax preparation · filing · reporting systems</td>
              </tr>
            </tbody>
          </table>
          <div className="text-xs text-slate-500 italic">
            Roger reads from TDC only. IMS receives outbound outputs only — it does not read from the platform.
          </div>
          <div className="text-xs text-slate-600">
            <span className="font-semibold">API Contracts:</span> vNormalizedTb (PDC) · TDC Records API · vRollforward · vFinalTaxReady · vReturnSummary
          </div>
        </div>
      </div>

      {/* ── End-to-End Audit Traceability — Lineage Chain ───────────────────── */}
      <div className="border border-slate-200 rounded-xl bg-white px-5 py-4 mb-3">
        <div className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-3">
          End-to-End Audit Traceability — Lineage Chain
        </div>
        <div className="flex flex-wrap items-start gap-1">
          {[
            { id: "DocumentId (GUID)", system: "Tax Portal", note: "Immutable · Lineage anchor" },
            { id: "JobId (GUID)", system: "Tax Portal", note: "Assigned at ingestion" },
            { id: "SourceRecordId (GUID)", system: "PDC", note: "GUID · Normalization" },
            { id: "FirmTaxonomyId (GUID)", system: "PDC / Taxonomy Svc", note: "REQUIRED · Classification" },
            { id: "RunId (GUID)", system: "PDC", note: "Batch traceability" },
            { id: "TdcRecordId (GUID)", system: "TDC", note: "GUID · Tax Record" },
            { id: "FilingId (GUID)", system: "TDC / Roger", note: "Immutable · Filed return" },
          ].map((item, i, arr) => (
            <span key={item.id} className="flex items-center gap-1">
              <div className="border border-blue-200 bg-blue-50 rounded px-3 py-2 text-center min-w-[100px]">
                <div className="text-xs font-bold text-blue-800">{item.id}</div>
                <div className="text-xs text-slate-500">{item.system}</div>
                <div className="text-xs text-slate-400 italic">{item.note}</div>
              </div>
              {i < arr.length - 1 && <ArrowRight className="w-3 h-3 text-slate-400 shrink-0" />}
            </span>
          ))}
        </div>
      </div>

      {/* ── Touchpoint Legend ────────────────────────────────────────────────── */}
      <div className="border border-slate-200 rounded-xl overflow-hidden">
        <div className="bg-[#1e3a5f] px-5 py-3 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="text-sm font-bold text-white">Touchpoint Legend</span>
            <span className="text-xs bg-blue-500 text-white px-2 py-0.5 rounded font-bold">T1 – T10</span>
          </div>
          <div className="text-xs text-blue-300">Hover any badge in the diagram to see details · Source: TOUCHPOINTS model</div>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-xs">
            <thead>
              <tr className="bg-slate-100 border-b border-slate-200">
                {["ID","Touchpoint Name","Step","Batch","System","Description"].map(h => (
                  <th key={h} className="text-left py-2 px-3 font-semibold text-slate-600 uppercase tracking-wide">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {TP_LEGEND_DATA.map((tp, i) => (
                <tr
                  key={tp.id}
                  onClick={() => setSelectedTp(selectedTp === tp.id ? null : tp.id)}
                  className={`border-b border-slate-100 cursor-pointer transition-colors ${
                    selectedTp === tp.id ? "bg-blue-50" : i % 2 === 0 ? "bg-white" : "bg-slate-50"
                  } hover:bg-blue-50`}
                >
                  <td className="py-2 px-3">
                    <span className="inline-flex items-center justify-center w-7 h-7 rounded-full bg-[#1e3a5f] text-white text-xs font-bold">{tp.id}</span>
                  </td>
                  <td className="py-2 px-3 font-medium text-slate-800">{tp.name}</td>
                  <td className="py-2 px-3 text-slate-500">{tp.step}</td>
                  <td className="py-2 px-3 text-slate-500">{tp.batch}</td>
                  <td className="py-2 px-3 text-slate-500">{tp.system}</td>
                  <td className="py-2 px-3 text-slate-500 max-w-xs">
                    {selectedTp === tp.id ? tp.desc : tp.desc.slice(0, 70) + "..."}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* ── Simulation Panel Overlay ── */}
      {simOpen && <SimulationPanel onClose={() => setSimOpen(false)} />}

    </div>
  );
}

// ─── MAIN PAGE ────────────────────────────────────────────────────────────────

export default function ArchitectureView() {
  const [selectedTp, setSelectedTp] = useState<string | null>(null);

  type TabId = "visio" | "platform" | "interactive" | "adrs" | "openitems" | "dependencies";
  const VALID_TABS: TabId[] = ["visio", "platform", "interactive", "adrs", "openitems", "dependencies"];

  const getTabFromUrl = (): TabId => {
    const params = new URLSearchParams(window.location.search);
    const t = params.get("tab") as TabId;
    return VALID_TABS.includes(t) ? t : "visio";
  };

  const [activeTab, setActiveTab] = useState<TabId>(getTabFromUrl);

  // React to URL changes (e.g. sidebar navigation with ?tab= param)
  useEffect(() => {
    const handlePopState = () => setActiveTab(getTabFromUrl());
    window.addEventListener("popstate", handlePopState);
    // Also check on mount in case Wouter already updated the URL
    setActiveTab(getTabFromUrl());
    return () => window.removeEventListener("popstate", handlePopState);
  }, [window.location.search]);

  const tpsByLayer = (layerId: string) =>
    TOUCHPOINTS.filter(tp => tp.layerId === layerId);

  return (
    <div className="p-6 space-y-5">
      {/* Source of Truth Governance Notice */}
      <div className="bg-amber-50 border border-amber-200 rounded-xl px-4 py-3 flex items-start gap-3">
        <div className="w-5 h-5 rounded-full bg-amber-400 flex items-center justify-center shrink-0 mt-0.5">
          <Shield className="w-3 h-3 text-white" />
        </div>
        <div>
          <div className="text-xs font-bold text-amber-900">Visio Architecture is the Single Source of Truth</div>
          <div className="text-xs text-amber-800 mt-0.5">
            All platform representations — layers, touchpoints, agents, ADRs, open items, and dashboard visualizations — derive from the DCT Roger End-to-End Data Flow Visio diagram.
            If the Visio changes, the model and dashboard must update. No other artifact overrides the Visio architecture.
          </div>
        </div>
        <div className="flex items-center gap-2 shrink-0 ml-auto">
          <span className="text-xs bg-emerald-100 text-emerald-800 border border-emerald-200 px-2 py-0.5 rounded-full font-semibold">Synced</span>
          <span className="text-xs bg-[#003A8F]/10 text-[#003A8F] border border-[#003A8F]/20 px-2 py-0.5 rounded-full font-semibold">v{ARCH_METADATA.version}</span>
        </div>
      </div>

      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-lg font-bold text-foreground">Platform Architecture</h1>
          <p className="text-xs text-muted-foreground mt-0.5">
            {ARCH_METADATA.layerCount} layers · {ARCH_METADATA.touchpointCount} touchpoints · {ARCH_METADATA.agentCount} AI agents · {ARCH_METADATA.adrCount} ADRs · {ARCH_METADATA.openItemCount} open items
          </p>
        </div>
        <div className="flex items-center gap-2 flex-wrap">
          <span className="text-xs bg-[#003A8F]/10 text-[#003A8F] border border-[#003A8F]/20 px-2.5 py-1 rounded-full font-semibold">
            Source: {ARCH_METADATA.sourceOfTruth}
          </span>
          <span className="text-xs text-muted-foreground text-xs">{ARCH_METADATA.lastUpdated}</span>
        </div>
      </div>

      {/* Architecture Guardrails Banner */}
      <div className="bg-[#0F2A5C] rounded-xl px-5 py-3">
        <div className="flex items-center justify-between mb-2">
          <div className="text-xs font-bold uppercase tracking-widest text-blue-300">Architecture Guardrails — Non-Negotiable Platform Invariants</div>
          <span className="text-xs text-blue-400 font-medium">Defined by Visio · Enforced by all agents</span>
        </div>
        <div className="flex flex-wrap gap-x-6 gap-y-1">
          {ARCHITECTURE_GUARDRAILS.map(g => (
            <div key={g.id} className="flex items-center gap-1.5">
              <span className="text-xs font-bold text-blue-400">{g.id}</span>
              <span className="text-xs text-blue-100">{g.rule}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Tab switcher */}
      <div className="flex flex-wrap gap-1 bg-slate-100 rounded-xl p-1 w-fit">
        <button
          onClick={() => setActiveTab("visio")}
          className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-semibold transition-all ${
            activeTab === "visio"
              ? "bg-white text-[#003A8F] shadow-sm border border-border"
              : "text-muted-foreground hover:text-foreground"
          }`}
        >
          <Image className="w-3.5 h-3.5" />
          Visio Diagram
          <span className="text-xs bg-[#003A8F]/10 text-[#003A8F] px-1.5 py-0.5 rounded font-medium">Sync Agent</span>
        </button>
        <button
          onClick={() => setActiveTab("platform")}
          className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-semibold transition-all ${
            activeTab === "platform"
              ? "bg-white text-[#065F46] shadow-sm border border-border"
              : "text-muted-foreground hover:text-foreground"
          }`}
        >
          <Layers className="w-3.5 h-3.5" />
          Full Platform Architecture
          <span className="text-xs bg-green-100 text-green-800 px-1.5 py-0.5 rounded font-medium">B0–B10</span>
        </button>
        <button
          onClick={() => { setActiveTab("interactive"); setSelectedTp(null); }}
          className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-semibold transition-all ${
            activeTab === "interactive"
              ? "bg-white text-[#003A8F] shadow-sm border border-border"
              : "text-muted-foreground hover:text-foreground"
          }`}
        >
          <Layers className="w-3.5 h-3.5" />
          Interactive Swimlane
        </button>
        {(["adrs", "openitems", "dependencies"] as const).map(tab => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-semibold transition-all ${
              activeTab === tab
                ? "bg-white text-[#003A8F] shadow-sm border border-border"
                : "text-muted-foreground hover:text-foreground"
            }`}
          >
            {tab === "adrs" && <><Shield className="w-3.5 h-3.5" />ADRs <span className="text-xs bg-[#003A8F]/10 text-[#003A8F] px-1.5 py-0.5 rounded">{ARCH_METADATA.adrCount}</span></>}
            {tab === "openitems" && <><FileText className="w-3.5 h-3.5" />Open Items <span className="text-xs bg-amber-100 text-amber-800 px-1.5 py-0.5 rounded">{ARCH_METADATA.openItemCount}</span></>}
            {tab === "dependencies" && <><Link2 className="w-3.5 h-3.5" />Dependencies <span className="text-xs bg-red-100 text-red-800 px-1.5 py-0.5 rounded">{ARCH_METADATA.dependencyCount}</span></>}
          </button>
        ))}
      </div>

      {/* Tab content */}
      <AnimatePresence mode="wait">
        {activeTab === "visio" && (
          <motion.div key="visio" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}>
            <VisioDiagramTab />
          </motion.div>
        )}
        {activeTab === "platform" && (
          <motion.div key="platform" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}>
            <div className="space-y-4">
              <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
                {[
                  { label: "PDC", sub: "Financial System of Record", color: "bg-emerald-50 border-emerald-300 text-emerald-800" },
                  { label: "TDC", sub: "Tax System of Record", color: "bg-orange-50 border-orange-300 text-orange-800" },
                  { label: "Taxonomy Service", sub: "Owned by DCT/TDC · FirmTaxonomyId authority · Hierarchy & versioning", color: "bg-violet-50 border-violet-300 text-violet-800" },
                  { label: "Roger", sub: "Read-Only Consumer · All via API Gateway", color: "bg-purple-50 border-purple-300 text-purple-800" },
                ].map(r => (
                  <div key={r.label} className={`border rounded-lg px-3 py-2 ${r.color}`}>
                    <div className="text-xs font-bold">{r.label}</div>
                    <div className="text-xs opacity-80">{r.sub}</div>
                  </div>
                ))}
              </div>
              <div className="rounded-2xl overflow-hidden border border-border bg-card">
                <div className="flex items-center justify-between px-4 py-3 bg-[#065F46] text-white">
                  <div>
                    <div className="font-semibold text-sm">DCT Platform — Full Stack Architecture · Batches 0–10</div>
                    <div className="text-xs text-green-200 mt-0.5">Roger · TDC · PDC · Service Bus · AI Orchestrator · API Gateway · Lineage</div>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-xs bg-green-800/60 text-green-200 px-2 py-0.5 rounded">v1.0 · 2026-03-12</span>
                    <a href={PLATFORM_ARCH_CDN_URL} download="DCT_Platform_Architecture_v1.png" target="_blank" rel="noopener noreferrer"
                      className="w-7 h-7 rounded flex items-center justify-center hover:bg-white/20 text-white transition-colors" title="Download PNG">
                      <Download className="w-3.5 h-3.5" />
                    </a>
                  </div>
                </div>
                <ZoomPanViewer src={PLATFORM_ARCH_CDN_URL} alt="DCT Platform Full Stack Architecture Batches 0-10" />
                <div className="px-4 py-2 bg-muted/30 border-t border-border flex items-center justify-between">
                  <div className="text-xs text-muted-foreground">DCT_Platform_Architecture_v1.png · Batch Roadmap B0–B10 · RSM | CATT · 2026-03-12</div>
                  <div className="flex gap-3 text-xs">
                    <span className="text-green-700 font-medium">PDC — Financial System of Record</span>
                    <span className="text-orange-700 font-medium">TDC — Tax System of Record</span>
                    <span className="text-purple-700 font-medium">Roger — Read-Only Consumer</span>
                  </div>
                </div>
              </div>
            </div>
          </motion.div>
        )}
        {activeTab === "interactive" && (
          <motion.div key="interactive" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}>
            <div className="flex gap-5 items-start">
              <div className="flex-1 space-y-2">
                <div className="bg-slate-900 rounded-2xl p-4 space-y-2">
                  <div className="text-xs font-semibold uppercase tracking-widest text-slate-400 mb-3 px-1">
                    DCT Platform Architecture Stack — T1–T11 Runtime Flow · Click any touchpoint for detail
                  </div>
                  {PLATFORM_LAYERS.map((layer, i) => (
                    <div key={layer.id}>
                      <LayerRow layer={layer} touchpoints={tpsByLayer(layer.id)} selectedTp={selectedTp} onSelectTp={setSelectedTp} />
                      {i < PLATFORM_LAYERS.length - 1 && (
                        <div className="flex justify-center py-1"><ArrowDown className="w-4 h-4 text-slate-500" /></div>
                      )}
                    </div>
                  ))}
                </div>
                <ArchitectureRules />
              </div>
              <AnimatePresence>
                {selectedTp && <TouchpointDetailPanel tpId={selectedTp} onClose={() => setSelectedTp(null)} />}
              </AnimatePresence>
            </div>
          </motion.div>
        )}
        {activeTab === "adrs" && (
          <motion.div key="adrs" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}>
            <div className="space-y-3">
              <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Architecture Decision Records — {ADR_REGISTRY.length} decisions</div>
              {ADR_REGISTRY.map(adr => (
                <div key={adr.id} className="bg-white border border-border rounded-xl p-5 space-y-2">
                  <div className="flex items-start justify-between gap-3 flex-wrap">
                    <div className="flex items-center gap-2">
                      <span className="text-xs font-bold text-[#003A8F] bg-[#003A8F]/10 px-2 py-0.5 rounded">{adr.id}</span>
                      <span className="font-semibold text-foreground text-sm">{adr.title}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium border ${
                        adr.status === "ACCEPTED" ? "bg-emerald-50 text-emerald-800 border-emerald-200" :
                        adr.status === "PROPOSED" ? "bg-amber-50 text-amber-800 border-amber-200" :
                        "bg-slate-100 text-slate-600 border-slate-200"
                      }`}>{adr.status}</span>
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium border ${
                        adr.impact === "High" ? "bg-red-50 text-red-800 border-red-200" :
                        adr.impact === "Medium" ? "bg-amber-50 text-amber-800 border-amber-200" :
                        "bg-slate-100 text-slate-600 border-slate-200"
                      }`}>{adr.impact} Impact</span>
                      <span className="text-xs text-muted-foreground">{adr.date}</span>
                    </div>
                  </div>
                  <p className="text-sm text-muted-foreground leading-relaxed">{adr.decision}</p>
                </div>
              ))}
            </div>
          </motion.div>
        )}
        {activeTab === "openitems" && (
          <motion.div key="openitems" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}>
            <div className="space-y-3">
              <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Open Architecture Items — {OPEN_ITEMS.length} items requiring resolution</div>
              {OPEN_ITEMS.map(item => (
                <div key={item.id} className="bg-white border border-border rounded-xl p-5 space-y-2">
                  <div className="flex items-start justify-between gap-3 flex-wrap">
                    <div className="flex items-center gap-2">
                      <span className="text-xs font-bold text-amber-700 bg-amber-50 border border-amber-200 px-2 py-0.5 rounded">{item.id}</span>
                      <span className="font-semibold text-foreground text-sm">{item.title}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium border ${
                        item.priority === "High" ? "bg-red-50 text-red-800 border-red-200" :
                        item.priority === "Medium" ? "bg-amber-50 text-amber-800 border-amber-200" :
                        "bg-slate-100 text-slate-600 border-slate-200"
                      }`}>{item.priority} Priority</span>
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium border ${
                        item.status === "OPEN" ? "bg-red-50 text-red-800 border-red-200" :
                        item.status === "IN_REVIEW" ? "bg-amber-50 text-amber-800 border-amber-200" :
                        "bg-emerald-50 text-emerald-800 border-emerald-200"
                      }`}>{item.status}</span>
                    </div>
                  </div>
                  <p className="text-sm text-muted-foreground leading-relaxed">{item.description}</p>
                  <div className="text-xs text-muted-foreground">Owner: <span className="font-medium text-foreground">{item.owner}</span></div>
                </div>
              ))}
            </div>
          </motion.div>
        )}
        {activeTab === "dependencies" && (
          <motion.div key="dependencies" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}>
            <div className="space-y-3">
              <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Platform Dependencies — {DEPENDENCIES.length} tracked</div>

              {/* Batch 2A blocking callout */}
              <div className="bg-amber-50 border border-amber-200 rounded-xl px-4 py-3 flex items-start gap-3">
                <span className="text-amber-500 text-base shrink-0 mt-0.5">⚠</span>
                <div>
                  <div className="text-xs font-bold text-amber-800 mb-0.5">Batch 2A — FirmTaxonomyId Enforcement Gate</div>
                  <div className="text-xs text-amber-700">DEP-04 (Taxonomy Service API contract) is currently <strong>BLOCKED</strong> and is a hard prerequisite for Batch 2A gate closure. The AI Orchestrator (Agent 3) cannot return FirmTaxonomyId until this contract is published and versioned. PDC will not issue READY signals for unclassified records once enforcement is active.</div>
                </div>
              </div>

              {DEPENDENCIES.map(dep => (
                <div key={dep.id} className={`bg-white border rounded-xl p-5 space-y-2 ${
                  dep.id === "DEP-04" ? "border-amber-300 bg-amber-50/30" :
                  dep.blocking ? "border-red-200" : "border-border"
                }`}>
                  <div className="flex items-start justify-between gap-3 flex-wrap">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="text-xs font-bold text-blue-700 bg-blue-50 border border-blue-200 px-2 py-0.5 rounded">{dep.id}</span>
                      <span className="font-semibold text-foreground text-sm">{dep.name}</span>
                      {dep.blocking && (
                        <span className="text-xs bg-red-100 text-red-800 border border-red-200 px-2 py-0.5 rounded-full font-bold">BLOCKING</span>
                      )}
                      {dep.id === "DEP-04" && (
                        <span className="text-xs bg-violet-100 text-violet-800 border border-violet-200 px-2 py-0.5 rounded-full font-bold">Batch 2A</span>
                      )}
                    </div>
                    <span className={`text-xs px-2 py-0.5 rounded-full font-medium border ${
                      dep.status === "IN_PROGRESS" ? "bg-blue-50 text-blue-800 border-blue-200" :
                      dep.status === "PLANNED" ? "bg-slate-100 text-slate-600 border-slate-200" :
                      dep.status === "COMPLETE" ? "bg-emerald-50 text-emerald-800 border-emerald-200" :
                      "bg-red-50 text-red-800 border-red-200"
                    }`}>{dep.status}</span>
                  </div>
                  <p className="text-sm text-muted-foreground leading-relaxed">{dep.description}</p>
                  <div className="text-xs text-muted-foreground">Owner: <span className="font-medium text-foreground">{dep.owner}</span></div>
                </div>
              ))}

              {/* Entry Points & Ingestion Contract */}
              <div className="bg-[#003A8F]/5 border border-[#003A8F]/20 rounded-xl p-5 space-y-3">
                <div className="text-xs font-bold uppercase tracking-wider text-[#003A8F]">Ingestion Contract — Enforced by Tax Portal</div>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <div className="text-xs font-semibold text-muted-foreground mb-1">Required Fields</div>
                    <div className="flex gap-2 flex-wrap">
                      {INGESTION_CONTRACT.requiredFields.map(f => (
                        <span key={f} className="text-xs bg-[#003A8F] text-white px-2 py-0.5 rounded font-mono">{f}</span>
                      ))}
                    </div>
                  </div>
                  <div>
                    <div className="text-xs font-semibold text-muted-foreground mb-1">Rejection Rule</div>
                    <div className="text-xs text-foreground">{INGESTION_CONTRACT.rejectionRule}</div>
                  </div>
                </div>
                <div>
                  <div className="text-xs font-semibold text-muted-foreground mb-2">Entry Points → Tax Portal</div>
                  <div className="flex gap-2 flex-wrap">
                    {ENTRY_POINTS.map(ep => (
                      <div key={ep.name} className="bg-white border border-[#003A8F]/20 rounded-lg px-3 py-1.5">
                        <div className="text-xs font-semibold text-[#003A8F]">{ep.name}</div>
                        <div className="text-xs text-muted-foreground">{ep.description}</div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {/* System Ownership */}
              <div className="bg-white border border-border rounded-xl p-5">
                <div className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-3">System Ownership Model</div>
                <div className="space-y-2">
                  {SYSTEM_OWNERSHIP.map(sys => (
                    <div key={sys.system} className="flex items-center gap-3 py-2 border-b border-border last:border-0">
                      <div className="w-3 h-3 rounded-full shrink-0" style={{ backgroundColor: sys.colorHex }} />
                      <div className="w-28 font-semibold text-sm text-foreground shrink-0">{sys.system}</div>
                      <div className="text-xs text-muted-foreground flex-1">{sys.role}</div>
                      <div className="text-xs text-muted-foreground shrink-0">{sys.owner}</div>
                      {sys.sor && (
                        <span className="text-xs bg-emerald-100 text-emerald-800 border border-emerald-200 px-2 py-0.5 rounded-full font-bold shrink-0">SOR</span>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <footer className="pt-4 pb-2 border-t border-border">
        <div className="flex items-center justify-between text-xs text-muted-foreground">
          <span>DCT Platform Architecture View · RSM | CATT · v3.2 · FirmTaxonomyId + Batch 2A</span>
          <span>Visio diagram: Architecture Sync Agent · Interactive: platformData.ts</span>
        </div>
      </footer>
    </div>
  );
}
