import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

describe("Provision and State Discovery refinement model", () => {
  it("keeps the State and Provision source models while removing the requested legacy sections from the rendered workspace", () => {
    const source = readFileSync(resolve(process.cwd(), "client/src/pages/onboarding/DiscoveryWorkspace.tsx"), "utf8");
    const buddySource = readFileSync(resolve(process.cwd(), "server/discoveryKnowledgeBase.ts"), "utf8");
    const stateStoriesBlock = source.slice(source.indexOf("const STATE_STORIES"), source.indexOf("const PROVISION_STORIES"));
    const stateCapabilitiesBlock = source.slice(source.indexOf("const STATE_CAPABILITY_ROWS"), source.indexOf("const PROVISION_CAPABILITY_ROWS"));
    const workstreamReadinessBlock = source.slice(source.indexOf("function WorkstreamReadinessHub"), source.indexOf("// ─── PI 4 State delivery readiness"));
    const renderedWorkspace = source.slice(source.indexOf("export default function DiscoveryWorkspace"));
    const postPilot = readFileSync(resolve(process.cwd(), "client/src/pages/PostPilotPage.tsx"), "utf8");

    expect(source).toContain("Cross-Team Discovery & Refinement Model");
    expect(source).not.toContain("DCT acceptance check");
    expect(source).not.toContain("Is there enough information in this story for DCT DEV");
    expect(stateStoriesBlock).toContain("1472734 – DCT Gateway — Compose State Return-Filing Response for Roger");
    expect(stateStoriesBlock).toContain("1471480 – DCT — Retrieve Return Structure Starting Context for a State Filer / Filing Group");
    expect(stateStoriesBlock.match(/estimation: "Ready with Dependency"/g)).toHaveLength(2);
    expect(stateStoriesBlock.match(/acceptance: "Ready"/g)).toHaveLength(2);
    expect(stateStoriesBlock).toContain('owner: "DCT"');
    expect(source).toContain("TIM provides the filer, State activation, deliverables, and the Single/Consolidated indicator");
    expect(source).toContain("Deliverable Due Date is the source for the date shown on the screen.");
    expect(source).toContain("The State filing group begins with an available Federal filing group");
    expect(source).toContain("State Story Refinement &amp; Ownership");
    expect(source).toContain("✓ Refined · DCT owned");
    expect(source).toContain("Managed State Delivery Dependencies");
    expect(source).toContain("DCT Delivery Guardrails");
    expect(source).toContain("Ownership Decision");
    expect(source).toContain("DCT has taken ownership of both refined State stories.");
    expect(source).toContain("Business requirement → 1472734 → 1471480 → Roger State Filing Experience");
    expect(source).toContain("not a strict technical predecessor sequence");
    expect(stateCapabilitiesBlock).toContain("State Return-Filing Data contract to be defined");
    expect(stateCapabilitiesBlock).toContain("State Filing Footprint lifecycle contract to be defined");
    expect(source).not.toContain("1471493");
    expect(source).not.toContain("1471498");

    expect(source).toContain("1479949 — DCT-P1-01: Provide governed RTP inputs, context, and source evidence");
    expect(source).toContain("1480251 — DCT-P1-03: Persist, audit, and recalculate prior-year amount corrections");
    expect(source).toContain("RTP Difference = PY Tax Return − PY Provision");
    expect(source).toContain("Package 1 — Return-to-Provision Review");
    expect(source).toContain("Annual Federal C corporation data");
    expect(source).toContain("Quarterly / interim provisions");
    expect(source).toContain("Package 0 — Federal Provision Data, Lineage, and Prior-Year Readiness");
    expect(source).toContain("Package 2 — Deferred Rollforward");
    expect(source).toContain("Package 3 — Federal Summary");
    expect(source).toContain("Provision Refinement Question Framework");
    expect(source).toContain("Primary Provision refinement prompts");
    expect(source).toContain("Downstream output contract and payable / deferred routing require confirmation.");
    expect(source).toContain("Provision Delivery Readiness");
    expect(source).toContain("Provision delivery path and readiness gates");
    expect(source).toContain("Current Provision Story Sizing & Estimation Assessment");
    expect(source).toContain("function PI4StateReadiness()");
    expect(source).toContain("function ProvisionDeliveryReadiness()");
    expect(source).toContain("How DCT Supports State Stories");
    expect(source).toContain("How DCT Supports Provision Stories");
    expect(source).toContain("Story Readiness Matrix");
    expect(source).toContain("Ready with Dependency");
    expect(source).toContain("Reusable Refinement Question Framework");
    expect(source).toContain("DCT must not select correction meaning");
    expect(source).toContain("State — File Drop + GoSystem Calculation System Flow");
    expect(source).toContain("GoSystem POC calculation extension");
    expect(source).toContain("Provision — File Drop End-to-End System Flow");
    expect(source).toContain("DMS / Original Document Storage");
    expect(source).toContain("Audit / Lineage (B16) connects to PDC and TDC.");
    expect(source).toContain("Package 2 Deferred Rollforward, Package 3 Federal Summary");
    expect(source).toContain("Copy system flow");
    expect(source).toContain('<ResponsibilityMatrix workstream="state" />');
    expect(source).toContain('const PROVISION_PROTOTYPE_URL = "https://rogertaxpro-bkwikmrm.manus.space/"');
    expect(source).toContain("Provision Prototype");
    expect(source).toContain("Roger — Tax Provision Prototype");
    expect(source).toContain("Interactive Roger Provision prototype used to illustrate the proposed Provision workflow, screen sequence, Return-to-Provision experience, Deferred Rollforward, and related practitioner interactions.");
    expect(source).toContain("Open Provision Prototype");
    expect(source).toContain('target="_blank"');
    expect(source).toContain('rel="noopener noreferrer"');
    expect(workstreamReadinessBlock.indexOf("<StoryMatrix stories={stories} />")).toBeLessThan(workstreamReadinessBlock.indexOf("<ProvisionPrototypeReference />"));
    expect(source).not.toContain("          <DiscoveryWorkflowSection />");
    expect(source).not.toContain("          <DataFlowSection />");
    expect(source).not.toContain("          <RuleProcessingTdcPosting />");
    expect(source).not.toContain("          <CapabilityMappingTable workstream={activeWorkstream} />");
    expect(source).not.toContain("          <DiscoveryQuestionsSection />");
    expect(source).not.toContain("          <DefinitionOfReadySection />");
    expect(source).not.toContain('SectionHeading number="A" title="Cross-Team Discovery & Refinement Model"');
    expect(source).not.toContain('SectionHeading number="B" title="State & Provision Story Readiness"');
    expect(source).not.toContain('SectionHeading number="PI4" title="Provision Delivery Readiness"');
    expect(source).not.toContain('SectionHeading number="7" title="Ask Buddy"');
    expect(source).not.toContain("        <QuickLinks />");

    expect(renderedWorkspace).not.toContain("<CrossTeamRefinementModel />");
    expect(renderedWorkspace).not.toContain("<WorkstreamReadinessHub");
    expect(renderedWorkspace).not.toContain("<PI4StateReadiness />");
    expect(renderedWorkspace).not.toContain("<ProvisionDeliveryReadiness />");
    expect(renderedWorkspace).not.toContain("activeWorkstream");
    expect(renderedWorkspace).not.toContain("A practical discovery and refinement workspace for State and Provision");
    expect(renderedWorkspace).not.toContain("Discovery Principle");
    expect(renderedWorkspace).not.toContain("Batch 9A — Gateway");
    expect(renderedWorkspace).toContain("<WorkstreamOverview />");
    expect(renderedWorkspace).toContain('<ResponsibilityMatrix workstream="state" />');
    expect(renderedWorkspace).not.toContain("<StateGoSystemPoc />");
    expect(renderedWorkspace).not.toContain("<StatePocBaDiscoveryPackage />");
    expect(renderedWorkspace).toContain("<ExistingCapabilities />");
    expect(renderedWorkspace).toContain("<AskBuddySection />");
    expect(postPilot.indexOf("<StateGoSystemPoc />")).toBeGreaterThan(postPilot.indexOf("Post Pilot feature inventory"));
    expect(buddySource).toContain("State Refinement & DCT Ownership — Current Two Backend Stories");
    expect(buddySource).toContain("Both stories are refined and **DCT-owned**");
    expect(buddySource).toContain("Roger owns practitioner-facing UI and actions but does not own State tax records.");
  });
});
