import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

describe("Provision and State Discovery refinement model", () => {
  it("keeps the supplied cross-team ownership, readiness rule, State, and Provision story discovery content", () => {
    const source = readFileSync(resolve(process.cwd(), "client/src/pages/onboarding/DiscoveryWorkspace.tsx"), "utf8");

    expect(source).toContain("Cross-Team Discovery & Refinement Model");
    expect(source).not.toContain("DCT acceptance check");
    expect(source).not.toContain("Is there enough information in this story for DCT DEV");
    expect(source).toContain("1471480 — Retrieve Return Structure Starting Context for a State Filer / Filing Group");
    expect(source).toContain("1472734 — DCT Gateway: Compose State Return-Filing Response for Roger");
    expect(source).toContain("1479949 — DCT-P1-01: Provide governed RTP inputs, context, and source evidence");
    expect(source).toContain("1480251 — DCT-P1-03: Persist, audit, and recalculate prior-year amount corrections");
    expect(source).toContain("RTP Difference = PY Tax Return − PY Provision");
    expect(source).toContain("Package 1 — Return-to-Provision Review");
    expect(source).toContain("Annual Federal C corporation data");
    expect(source).toContain("Quarterly / interim provisions");
    expect(source).toContain("Package 0 — Federal Provision Data, Lineage, and Prior-Year Readiness");
    expect(source).toContain("Package 2 — Deferred Rollforward");
    expect(source).toContain("Package 3 — Federal Summary");
    expect(source).toContain("Provision Refinement Question Framework");
    expect(source).toContain("Primary Provision refinement prompts");
    expect(source).toContain("Downstream output contract and payable / deferred routing require confirmation.");
    expect(source).toContain("Provision Delivery Readiness");
    expect(source).toContain("Provision delivery path and readiness gates");
    expect(source).toContain("Current Provision Story Sizing & Estimation Assessment");
    expect(source).toContain("activeWorkstream === \"state\" ? <PI4StateReadiness /> : <ProvisionDeliveryReadiness />");
    expect(source).toContain("How DCT Supports State Stories");
    expect(source).toContain("How DCT Supports Provision Stories");
    expect(source).toContain("1479949");
    expect(source).toContain("1471480");
    expect(source).toContain("Story Readiness Matrix");
    expect(source).toContain("Ready with Dependency");
    expect(source).toContain("Reusable Refinement Question Framework");
    expect(source).toContain("DCT must not select correction meaning");
    expect(source).toContain("State — File Drop End-to-End System Flow");
    expect(source).toContain("Provision — File Drop End-to-End System Flow");
    expect(source).toContain("DMS / Original Document Storage");
    expect(source).toContain("Audit / Lineage (B16) connects to PDC and TDC.");
    expect(source).toContain("Package 2 Deferred Rollforward, Package 3 Federal Summary");
    expect(source).toContain("Copy system flow");
    expect(source).toContain('<ResponsibilityMatrix workstream={activeWorkstream} />');
    expect(source).not.toContain("          <DiscoveryWorkflowSection />");
    expect(source).not.toContain("          <DataFlowSection />");
    expect(source).not.toContain("          <RuleProcessingTdcPosting />");
    expect(source).not.toContain("          <CapabilityMappingTable workstream={activeWorkstream} />");
    expect(source).not.toContain("          <DiscoveryQuestionsSection />");
    expect(source).not.toContain("          <DefinitionOfReadySection />");
    expect(source).not.toContain('SectionHeading number="A" title="Cross-Team Discovery & Refinement Model"');
    expect(source).not.toContain('SectionHeading number="B" title="State & Provision Story Readiness"');
    expect(source).not.toContain('SectionHeading number="PI4" title="Provision Delivery Readiness"');
    expect(source).not.toContain('SectionHeading number="7" title="Ask Buddy"');
    expect(source).not.toContain("        <QuickLinks />");
  });
});
